// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.0
// source: internal/signing/proto/signer.proto

package signerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Algorithm int32

const (
	Algorithm_ALGORITHM_UNSPECIFIED Algorithm = 0
	Algorithm_ALGORITHM_RSA_2048    Algorithm = 1
	Algorithm_ALGORITHM_RSA_3072    Algorithm = 2
	Algorithm_ALGORITHM_RSA_4096    Algorithm = 3
	Algorithm_ALGORITHM_ECDSA_P256  Algorithm = 4
	Algorithm_ALGORITHM_ECDSA_P384  Algorithm = 5
	Algorithm_ALGORITHM_ECDSA_P521  Algorithm = 6
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0: "ALGORITHM_UNSPECIFIED",
		1: "ALGORITHM_RSA_2048",
		2: "ALGORITHM_RSA_3072",
		3: "ALGORITHM_RSA_4096",
		4: "ALGORITHM_ECDSA_P256",
		5: "ALGORITHM_ECDSA_P384",
		6: "ALGORITHM_ECDSA_P521",
	}
	Algorithm_value = map[string]int32{
		"ALGORITHM_UNSPECIFIED": 0,
		"ALGORITHM_RSA_2048":    1,
		"ALGORITHM_RSA_3072":    2,
		"ALGORITHM_RSA_4096":    3,
		"ALGORITHM_ECDSA_P256":  4,
		"ALGORITHM_ECDSA_P384":  5,
		"ALGORITHM_ECDSA_P521":  6,
	}
)

func (x Algorithm) Enum() *Algorithm {
	p := new(Algorithm)
	*p = x
	return p
}

func (x Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_signing_proto_signer_proto_enumTypes[0].Descriptor()
}

func (Algorithm) Type() protoreflect.EnumType {
	return &file_internal_signing_proto_signer_proto_enumTypes[0]
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{0}
}

type Hash int32

const (
	Hash_HASH_UNSPECIFIED Hash = 0
	Hash_HASH_SHA256      Hash = 1
	Hash_HASH_SHA384      Hash = 2
	Hash_HASH_SHA512      Hash = 3
)

// Enum value maps for Hash.
var (
	Hash_name = map[int32]string{
		0: "HASH_UNSPECIFIED",
		1: "HASH_SHA256",
		2: "HASH_SHA384",
		3: "HASH_SHA512",
	}
	Hash_value = map[string]int32{
		"HASH_UNSPECIFIED": 0,
		"HASH_SHA256":      1,
		"HASH_SHA384":      2,
		"HASH_SHA512":      3,
	}
)

func (x Hash) Enum() *Hash {
	p := new(Hash)
	*p = x
	return p
}

func (x Hash) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hash) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_signing_proto_signer_proto_enumTypes[1].Descriptor()
}

func (Hash) Type() protoreflect.EnumType {
	return &file_internal_signing_proto_signer_proto_enumTypes[1]
}

func (x Hash) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hash.Descriptor instead.
func (Hash) EnumDescriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{1}
}

type RSAPadding int32

const (
	RSAPadding_RSA_PADDING_UNSPECIFIED RSAPadding = 0
	RSAPadding_RSA_PADDING_PKCS1V15    RSAPadding = 1
	RSAPadding_RSA_PADDING_PSS         RSAPadding = 2
)

// Enum value maps for RSAPadding.
var (
	RSAPadding_name = map[int32]string{
		0: "RSA_PADDING_UNSPECIFIED",
		1: "RSA_PADDING_PKCS1V15",
		2: "RSA_PADDING_PSS",
	}
	RSAPadding_value = map[string]int32{
		"RSA_PADDING_UNSPECIFIED": 0,
		"RSA_PADDING_PKCS1V15":    1,
		"RSA_PADDING_PSS":         2,
	}
)

func (x RSAPadding) Enum() *RSAPadding {
	p := new(RSAPadding)
	*p = x
	return p
}

func (x RSAPadding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RSAPadding) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_signing_proto_signer_proto_enumTypes[2].Descriptor()
}

func (RSAPadding) Type() protoreflect.EnumType {
	return &file_internal_signing_proto_signer_proto_enumTypes[2]
}

func (x RSAPadding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RSAPadding.Descriptor instead.
func (RSAPadding) EnumDescriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{2}
}

type KeyPurpose int32

const (
	KeyPurpose_KEY_PURPOSE_UNSPECIFIED KeyPurpose = 0
	KeyPurpose_KEY_PURPOSE_CA_SIGN     KeyPurpose = 1
	KeyPurpose_KEY_PURPOSE_LEAF_TLS    KeyPurpose = 2
	KeyPurpose_KEY_PURPOSE_SSH_CERT    KeyPurpose = 3
	KeyPurpose_KEY_PURPOSE_CODE_SIGN   KeyPurpose = 4
	KeyPurpose_KEY_PURPOSE_GENERIC     KeyPurpose = 5
)

// Enum value maps for KeyPurpose.
var (
	KeyPurpose_name = map[int32]string{
		0: "KEY_PURPOSE_UNSPECIFIED",
		1: "KEY_PURPOSE_CA_SIGN",
		2: "KEY_PURPOSE_LEAF_TLS",
		3: "KEY_PURPOSE_SSH_CERT",
		4: "KEY_PURPOSE_CODE_SIGN",
		5: "KEY_PURPOSE_GENERIC",
	}
	KeyPurpose_value = map[string]int32{
		"KEY_PURPOSE_UNSPECIFIED": 0,
		"KEY_PURPOSE_CA_SIGN":     1,
		"KEY_PURPOSE_LEAF_TLS":    2,
		"KEY_PURPOSE_SSH_CERT":    3,
		"KEY_PURPOSE_CODE_SIGN":   4,
		"KEY_PURPOSE_GENERIC":     5,
	}
)

func (x KeyPurpose) Enum() *KeyPurpose {
	p := new(KeyPurpose)
	*p = x
	return p
}

func (x KeyPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_signing_proto_signer_proto_enumTypes[3].Descriptor()
}

func (KeyPurpose) Type() protoreflect.EnumType {
	return &file_internal_signing_proto_signer_proto_enumTypes[3]
}

func (x KeyPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyPurpose.Descriptor instead.
func (KeyPurpose) EnumDescriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{3}
}

type HealthResponse_Status int32

const (
	HealthResponse_STATUS_UNSPECIFIED HealthResponse_Status = 0
	HealthResponse_STATUS_SERVING     HealthResponse_Status = 1
	HealthResponse_STATUS_NOT_SERVING HealthResponse_Status = 2
	HealthResponse_STATUS_DRAINING    HealthResponse_Status = 3
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SERVING",
		2: "STATUS_NOT_SERVING",
		3: "STATUS_DRAINING",
	}
	HealthResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_SERVING":     1,
		"STATUS_NOT_SERVING": 2,
		"STATUS_DRAINING":    3,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_signing_proto_signer_proto_enumTypes[4].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_internal_signing_proto_signer_proto_enumTypes[4]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{10, 0}
}

type KeyHandle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyHandle) Reset() {
	*x = KeyHandle{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyHandle) ProtoMessage() {}

func (x *KeyHandle) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyHandle.ProtoReflect.Descriptor instead.
func (*KeyHandle) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{0}
}

func (x *KeyHandle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GenerateKeyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Algorithm       Algorithm              `protobuf:"varint,1,opt,name=algorithm,proto3,enum=certctl.signing.v1.Algorithm" json:"algorithm,omitempty"`
	RequestedId     string                 `protobuf:"bytes,2,opt,name=requested_id,json=requestedId,proto3" json:"requested_id,omitempty"`
	AllowedPurposes []KeyPurpose           `protobuf:"varint,3,rep,packed,name=allowed_purposes,json=allowedPurposes,proto3,enum=certctl.signing.v1.KeyPurpose" json:"allowed_purposes,omitempty"`
	AllowedHashes   []Hash                 `protobuf:"varint,4,rep,packed,name=allowed_hashes,json=allowedHashes,proto3,enum=certctl.signing.v1.Hash" json:"allowed_hashes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateKeyRequest) Reset() {
	*x = GenerateKeyRequest{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyRequest) ProtoMessage() {}

func (x *GenerateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyRequest.ProtoReflect.Descriptor instead.
func (*GenerateKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateKeyRequest) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (x *GenerateKeyRequest) GetRequestedId() string {
	if x != nil {
		return x.RequestedId
	}
	return ""
}

func (x *GenerateKeyRequest) GetAllowedPurposes() []KeyPurpose {
	if x != nil {
		return x.AllowedPurposes
	}
	return nil
}

func (x *GenerateKeyRequest) GetAllowedHashes() []Hash {
	if x != nil {
		return x.AllowedHashes
	}
	return nil
}

type GenerateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *KeyHandle             `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Algorithm     Algorithm              `protobuf:"varint,2,opt,name=algorithm,proto3,enum=certctl.signing.v1.Algorithm" json:"algorithm,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKeyResponse) Reset() {
	*x = GenerateKeyResponse{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyResponse) ProtoMessage() {}

func (x *GenerateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyResponse.ProtoReflect.Descriptor instead.
func (*GenerateKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateKeyResponse) GetHandle() *KeyHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *GenerateKeyResponse) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (x *GenerateKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type GetPublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *KeyHandle             `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyRequest) Reset() {
	*x = GetPublicKeyRequest{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyRequest) ProtoMessage() {}

func (x *GetPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*GetPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{3}
}

func (x *GetPublicKeyRequest) GetHandle() *KeyHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

type GetPublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     Algorithm              `protobuf:"varint,1,opt,name=algorithm,proto3,enum=certctl.signing.v1.Algorithm" json:"algorithm,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyResponse) Reset() {
	*x = GetPublicKeyResponse{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyResponse) ProtoMessage() {}

func (x *GetPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{4}
}

func (x *GetPublicKeyResponse) GetAlgorithm() Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return Algorithm_ALGORITHM_UNSPECIFIED
}

func (x *GetPublicKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *KeyHandle             `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Hash          Hash                   `protobuf:"varint,3,opt,name=hash,proto3,enum=certctl.signing.v1.Hash" json:"hash,omitempty"`
	RsaPadding    RSAPadding             `protobuf:"varint,4,opt,name=rsa_padding,json=rsaPadding,proto3,enum=certctl.signing.v1.RSAPadding" json:"rsa_padding,omitempty"`
	Purpose       KeyPurpose             `protobuf:"varint,5,opt,name=purpose,proto3,enum=certctl.signing.v1.KeyPurpose" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{5}
}

func (x *SignRequest) GetHandle() *KeyHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

func (x *SignRequest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *SignRequest) GetHash() Hash {
	if x != nil {
		return x.Hash
	}
	return Hash_HASH_UNSPECIFIED
}

func (x *SignRequest) GetRsaPadding() RSAPadding {
	if x != nil {
		return x.RsaPadding
	}
	return RSAPadding_RSA_PADDING_UNSPECIFIED
}

func (x *SignRequest) GetPurpose() KeyPurpose {
	if x != nil {
		return x.Purpose
	}
	return KeyPurpose_KEY_PURPOSE_UNSPECIFIED
}

type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{6}
}

func (x *SignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type DestroyKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        *KeyHandle             `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyKeyRequest) Reset() {
	*x = DestroyKeyRequest{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyKeyRequest) ProtoMessage() {}

func (x *DestroyKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyKeyRequest.ProtoReflect.Descriptor instead.
func (*DestroyKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{7}
}

func (x *DestroyKeyRequest) GetHandle() *KeyHandle {
	if x != nil {
		return x.Handle
	}
	return nil
}

type DestroyKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyKeyResponse) Reset() {
	*x = DestroyKeyResponse{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyKeyResponse) ProtoMessage() {}

func (x *DestroyKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyKeyResponse.ProtoReflect.Descriptor instead.
func (*DestroyKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{8}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{9}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=certctl.signing.v1.HealthResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_signing_proto_signer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_signing_proto_signer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_signing_proto_signer_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_STATUS_UNSPECIFIED
}

var File_internal_signing_proto_signer_proto protoreflect.FileDescriptor

const file_internal_signing_proto_signer_proto_rawDesc = "" +
	"\n" +
	"#internal/signing/proto/signer.proto\x12\x12certctl.signing.v1\"\x1b\n" +
	"\tKeyHandle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x80\x02\n" +
	"\x12GenerateKeyRequest\x12;\n" +
	"\talgorithm\x18\x01 \x01(\x0e2\x1d.certctl.signing.v1.AlgorithmR\talgorithm\x12!\n" +
	"\frequested_id\x18\x02 \x01(\tR\vrequestedId\x12I\n" +
	"\x10allowed_purposes\x18\x03 \x03(\x0e2\x1e.certctl.signing.v1.KeyPurposeR\x0fallowedPurposes\x12?\n" +
	"\x0eallowed_hashes\x18\x04 \x03(\x0e2\x18.certctl.signing.v1.HashR\rallowedHashes\"\xa8\x01\n" +
	"\x13GenerateKeyResponse\x125\n" +
	"\x06handle\x18\x01 \x01(\v2\x1d.certctl.signing.v1.KeyHandleR\x06handle\x12;\n" +
	"\talgorithm\x18\x02 \x01(\x0e2\x1d.certctl.signing.v1.AlgorithmR\talgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\"L\n" +
	"\x13GetPublicKeyRequest\x125\n" +
	"\x06handle\x18\x01 \x01(\v2\x1d.certctl.signing.v1.KeyHandleR\x06handle\"r\n" +
	"\x14GetPublicKeyResponse\x12;\n" +
	"\talgorithm\x18\x01 \x01(\x0e2\x1d.certctl.signing.v1.AlgorithmR\talgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"\x85\x02\n" +
	"\vSignRequest\x125\n" +
	"\x06handle\x18\x01 \x01(\v2\x1d.certctl.signing.v1.KeyHandleR\x06handle\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\x12,\n" +
	"\x04hash\x18\x03 \x01(\x0e2\x18.certctl.signing.v1.HashR\x04hash\x12?\n" +
	"\vrsa_padding\x18\x04 \x01(\x0e2\x1e.certctl.signing.v1.RSAPaddingR\n" +
	"rsaPadding\x128\n" +
	"\apurpose\x18\x05 \x01(\x0e2\x1e.certctl.signing.v1.KeyPurposeR\apurpose\",\n" +
	"\fSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"J\n" +
	"\x11DestroyKeyRequest\x125\n" +
	"\x06handle\x18\x01 \x01(\v2\x1d.certctl.signing.v1.KeyHandleR\x06handle\"\x14\n" +
	"\x12DestroyKeyResponse\"\x0f\n" +
	"\rHealthRequest\"\xb6\x01\n" +
	"\x0eHealthResponse\x12A\n" +
	"\x06status\x18\x01 \x01(\x0e2).certctl.signing.v1.HealthResponse.StatusR\x06status\"a\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SERVING\x10\x01\x12\x16\n" +
	"\x12STATUS_NOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSTATUS_DRAINING\x10\x03*\xbc\x01\n" +
	"\tAlgorithm\x12\x19\n" +
	"\x15ALGORITHM_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ALGORITHM_RSA_2048\x10\x01\x12\x16\n" +
	"\x12ALGORITHM_RSA_3072\x10\x02\x12\x16\n" +
	"\x12ALGORITHM_RSA_4096\x10\x03\x12\x18\n" +
	"\x14ALGORITHM_ECDSA_P256\x10\x04\x12\x18\n" +
	"\x14ALGORITHM_ECDSA_P384\x10\x05\x12\x18\n" +
	"\x14ALGORITHM_ECDSA_P521\x10\x06*O\n" +
	"\x04Hash\x12\x14\n" +
	"\x10HASH_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vHASH_SHA256\x10\x01\x12\x0f\n" +
	"\vHASH_SHA384\x10\x02\x12\x0f\n" +
	"\vHASH_SHA512\x10\x03*X\n" +
	"\n" +
	"RSAPadding\x12\x1b\n" +
	"\x17RSA_PADDING_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RSA_PADDING_PKCS1V15\x10\x01\x12\x13\n" +
	"\x0fRSA_PADDING_PSS\x10\x02*\xaa\x01\n" +
	"\n" +
	"KeyPurpose\x12\x1b\n" +
	"\x17KEY_PURPOSE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13KEY_PURPOSE_CA_SIGN\x10\x01\x12\x18\n" +
	"\x14KEY_PURPOSE_LEAF_TLS\x10\x02\x12\x18\n" +
	"\x14KEY_PURPOSE_SSH_CERT\x10\x03\x12\x19\n" +
	"\x15KEY_PURPOSE_CODE_SIGN\x10\x04\x12\x17\n" +
	"\x13KEY_PURPOSE_GENERIC\x10\x052\xcb\x03\n" +
	"\rSignerService\x12^\n" +
	"\vGenerateKey\x12&.certctl.signing.v1.GenerateKeyRequest\x1a'.certctl.signing.v1.GenerateKeyResponse\x12a\n" +
	"\fGetPublicKey\x12'.certctl.signing.v1.GetPublicKeyRequest\x1a(.certctl.signing.v1.GetPublicKeyResponse\x12I\n" +
	"\x04Sign\x12\x1f.certctl.signing.v1.SignRequest\x1a .certctl.signing.v1.SignResponse\x12[\n" +
	"\n" +
	"DestroyKey\x12%.certctl.signing.v1.DestroyKeyRequest\x1a&.certctl.signing.v1.DestroyKeyResponse\x12O\n" +
	"\x06Health\x12!.certctl.signing.v1.HealthRequest\x1a\".certctl.signing.v1.HealthResponseB4Z2certctl.io/certctl/internal/signing/proto;signerpbb\x06proto3"

var (
	file_internal_signing_proto_signer_proto_rawDescOnce sync.Once
	file_internal_signing_proto_signer_proto_rawDescData []byte
)

func file_internal_signing_proto_signer_proto_rawDescGZIP() []byte {
	file_internal_signing_proto_signer_proto_rawDescOnce.Do(func() {
		file_internal_signing_proto_signer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_signing_proto_signer_proto_rawDesc), len(file_internal_signing_proto_signer_proto_rawDesc)))
	})
	return file_internal_signing_proto_signer_proto_rawDescData
}

var file_internal_signing_proto_signer_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_internal_signing_proto_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_signing_proto_signer_proto_goTypes = []any{
	(Algorithm)(0),               // 0: certctl.signing.v1.Algorithm
	(Hash)(0),                    // 1: certctl.signing.v1.Hash
	(RSAPadding)(0),              // 2: certctl.signing.v1.RSAPadding
	(KeyPurpose)(0),              // 3: certctl.signing.v1.KeyPurpose
	(HealthResponse_Status)(0),   // 4: certctl.signing.v1.HealthResponse.Status
	(*KeyHandle)(nil),            // 5: certctl.signing.v1.KeyHandle
	(*GenerateKeyRequest)(nil),   // 6: certctl.signing.v1.GenerateKeyRequest
	(*GenerateKeyResponse)(nil),  // 7: certctl.signing.v1.GenerateKeyResponse
	(*GetPublicKeyRequest)(nil),  // 8: certctl.signing.v1.GetPublicKeyRequest
	(*GetPublicKeyResponse)(nil), // 9: certctl.signing.v1.GetPublicKeyResponse
	(*SignRequest)(nil),          // 10: certctl.signing.v1.SignRequest
	(*SignResponse)(nil),         // 11: certctl.signing.v1.SignResponse
	(*DestroyKeyRequest)(nil),    // 12: certctl.signing.v1.DestroyKeyRequest
	(*DestroyKeyResponse)(nil),   // 13: certctl.signing.v1.DestroyKeyResponse
	(*HealthRequest)(nil),        // 14: certctl.signing.v1.HealthRequest
	(*HealthResponse)(nil),       // 15: certctl.signing.v1.HealthResponse
}
var file_internal_signing_proto_signer_proto_depIdxs = []int32{
	0,  // 0: certctl.signing.v1.GenerateKeyRequest.algorithm:type_name -> certctl.signing.v1.Algorithm
	3,  // 1: certctl.signing.v1.GenerateKeyRequest.allowed_purposes:type_name -> certctl.signing.v1.KeyPurpose
	1,  // 2: certctl.signing.v1.GenerateKeyRequest.allowed_hashes:type_name -> certctl.signing.v1.Hash
	5,  // 3: certctl.signing.v1.GenerateKeyResponse.handle:type_name -> certctl.signing.v1.KeyHandle
	0,  // 4: certctl.signing.v1.GenerateKeyResponse.algorithm:type_name -> certctl.signing.v1.Algorithm
	5,  // 5: certctl.signing.v1.GetPublicKeyRequest.handle:type_name -> certctl.signing.v1.KeyHandle
	0,  // 6: certctl.signing.v1.GetPublicKeyResponse.algorithm:type_name -> certctl.signing.v1.Algorithm
	5,  // 7: certctl.signing.v1.SignRequest.handle:type_name -> certctl.signing.v1.KeyHandle
	1,  // 8: certctl.signing.v1.SignRequest.hash:type_name -> certctl.signing.v1.Hash
	2,  // 9: certctl.signing.v1.SignRequest.rsa_padding:type_name -> certctl.signing.v1.RSAPadding
	3,  // 10: certctl.signing.v1.SignRequest.purpose:type_name -> certctl.signing.v1.KeyPurpose
	5,  // 11: certctl.signing.v1.DestroyKeyRequest.handle:type_name -> certctl.signing.v1.KeyHandle
	4,  // 12: certctl.signing.v1.HealthResponse.status:type_name -> certctl.signing.v1.HealthResponse.Status
	6,  // 13: certctl.signing.v1.SignerService.GenerateKey:input_type -> certctl.signing.v1.GenerateKeyRequest
	8,  // 14: certctl.signing.v1.SignerService.GetPublicKey:input_type -> certctl.signing.v1.GetPublicKeyRequest
	10, // 15: certctl.signing.v1.SignerService.Sign:input_type -> certctl.signing.v1.SignRequest
	12, // 16: certctl.signing.v1.SignerService.DestroyKey:input_type -> certctl.signing.v1.DestroyKeyRequest
	14, // 17: certctl.signing.v1.SignerService.Health:input_type -> certctl.signing.v1.HealthRequest
	7,  // 18: certctl.signing.v1.SignerService.GenerateKey:output_type -> certctl.signing.v1.GenerateKeyResponse
	9,  // 19: certctl.signing.v1.SignerService.GetPublicKey:output_type -> certctl.signing.v1.GetPublicKeyResponse
	11, // 20: certctl.signing.v1.SignerService.Sign:output_type -> certctl.signing.v1.SignResponse
	13, // 21: certctl.signing.v1.SignerService.DestroyKey:output_type -> certctl.signing.v1.DestroyKeyResponse
	15, // 22: certctl.signing.v1.SignerService.Health:output_type -> certctl.signing.v1.HealthResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_signing_proto_signer_proto_init() }
func file_internal_signing_proto_signer_proto_init() {
	if File_internal_signing_proto_signer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_signing_proto_signer_proto_rawDesc), len(file_internal_signing_proto_signer_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_signing_proto_signer_proto_goTypes,
		DependencyIndexes: file_internal_signing_proto_signer_proto_depIdxs,
		EnumInfos:         file_internal_signing_proto_signer_proto_enumTypes,
		MessageInfos:      file_internal_signing_proto_signer_proto_msgTypes,
	}.Build()
	File_internal_signing_proto_signer_proto = out.File
	file_internal_signing_proto_signer_proto_goTypes = nil
	file_internal_signing_proto_signer_proto_depIdxs = nil
}
