export type ApiWorkflowCoverageKind = "console-flow" | "api-explorer" | "api-cli-exception";

export interface ApiWorkflowCoverage {
  path: string;
  route: string;
  owner: string;
  kind: ApiWorkflowCoverageKind;
  workflow: string;
  rationale: string;
}

export const apiWorkflowCoverage = [
  {
    path: "/api/v1/access/sessions",
    route: "/integrate/api",
    owner: "SURFACE/access",
    kind: "api-cli-exception",
    workflow: "Access session ledger inspection",
    rationale: "The Platform page shows the current browser session and access administration; the full session ledger remains an operator/API workflow.",
  },
  {
    path: "/api/v1/access/sessions/{id}",
    route: "/integrate/api",
    owner: "SURFACE/access",
    kind: "api-cli-exception",
    workflow: "Access session detail inspection",
    rationale: "Session detail is not mutated from the browser console; operators use the API Explorer or CLI until a dedicated session-admin table lands.",
  },
  {
    path: "/api/v1/agents/{id}/cert-revocations",
    route: "/integrate/api",
    owner: "SURFACE/agents",
    kind: "api-explorer",
    workflow: "Agent certificate revocation receipt lookup",
    rationale:
      "The Agents page owns enrollment and fleet visibility; per-agent revocation receipts are exposed through the API Explorer for support workflows.",
  },
  {
    path: "/api/v1/ca/authorities",
    route: "/ca-hierarchy",
    owner: "SURFACE/ca",
    kind: "console-flow",
    workflow: "CA hierarchy inventory",
    rationale:
      "The CA Hierarchy page shows authority inventory, managed status, issuer visibility, and CA discovery evidence with loading, empty, and error states.",
  },
  {
    path: "/api/v1/ca/authorities/intermediates",
    route: "/integrate/api",
    owner: "SURFACE/ca",
    kind: "api-explorer",
    workflow: "Signer-backed intermediate CA creation",
    rationale: "The console has offline/import intermediate flows; direct signer-backed intermediate creation remains an API Explorer ceremony workflow.",
  },
  {
    path: "/api/v1/ca/authorities/roots",
    route: "/integrate/api",
    owner: "SURFACE/ca",
    kind: "api-explorer",
    workflow: "Signer-backed root CA creation",
    rationale:
      "The CA Hierarchy page starts root ceremonies; direct root authority creation is kept in the API Explorer until the ceremony UI binds this endpoint.",
  },
  {
    path: "/api/v1/ca/authorities/{id}/intermediates/csr",
    route: "/integrate/api",
    owner: "SURFACE/ca",
    kind: "api-explorer",
    workflow: "Issue intermediate CA from CSR",
    rationale: "The console has offline intermediate CSR import flow; online CSR issuance remains an API Explorer operator action.",
  },
  {
    path: "/api/v1/ca/authorities/{id}/issue",
    route: "/integrate/api",
    owner: "SURFACE/ca",
    kind: "api-explorer",
    workflow: "Issue leaf certificate from CA authority",
    rationale: "The Request Credential and Identities pages cover normal issuance; authority-specific leaf issue remains an advanced API Explorer action.",
  },
  {
    path: "/api/v1/ca/ceremonies/{id}",
    route: "/integrate/api",
    owner: "SURFACE/ca",
    kind: "api-explorer",
    workflow: "CA ceremony detail lookup",
    rationale: "The CA Hierarchy page displays newly started or approved ceremonies; arbitrary ceremony lookup is covered by the API Explorer.",
  },
  {
    path: "/api/v1/certificates/bulk-revoke",
    route: "/integrate/api",
    owner: "SURFACE/certificates",
    kind: "api-explorer",
    workflow: "Criteria-based certificate bulk revoke",
    rationale:
      "The console exposes certificate detail and identity revocation; criteria-based certificate bulk revoke stays in API Explorer/CLI until a guarded batch wizard lands.",
  },
  {
    path: "/api/v1/certificates/{id}",
    route: "/certificates",
    owner: "SURFACE/certificates",
    kind: "console-flow",
    workflow: "Certificate detail drawer",
    rationale: "The Certificates page opens a detail drawer via getCertificate with loading, permission, error, and populated states.",
  },
  {
    path: "/api/v1/connectors/catalog",
    route: "/connectors",
    owner: "SURFACE/connectors",
    kind: "console-flow",
    workflow: "Connector registry",
    rationale: "The Connectors page loads the connector catalog and shows empty/error states with target setup and action workflows.",
  },
  {
    path: "/api/v1/connectors/deliveries",
    route: "/connectors",
    owner: "SURFACE/connectors",
    kind: "console-flow",
    workflow: "Connector delivery receipt list",
    rationale: "The Connectors and Operations pages show recent delivery receipts, attempts, rollback references, and empty/error states.",
  },
  {
    path: "/api/v1/connectors/deliveries/{id}",
    route: "/integrate/api",
    owner: "SURFACE/connectors",
    kind: "api-explorer",
    workflow: "Connector delivery receipt detail",
    rationale: "Receipt lists are first-class in the console; arbitrary receipt detail by id is covered by the API Explorer.",
  },
  {
    path: "/api/v1/connectors/outbox-circuits",
    route: "/integrate/api",
    owner: "SURFACE/runops",
    kind: "api-explorer",
    workflow: "Outbox circuit breaker diagnostics",
    rationale: "The Operations queue shows delivery status; low-level outbox circuit state remains a support/operator diagnostic through the API Explorer.",
  },
  {
    path: "/api/v1/connectors/targets/{id}",
    route: "/connectors",
    owner: "SURFACE/connectors",
    kind: "console-flow",
    workflow: "Connector target actions",
    rationale: "The Connectors page lists targets and drives bind, test, deploy, and rollback actions against selected targets.",
  },
  {
    path: "/api/v1/discovery/findings",
    route: "/discovery",
    owner: "SURFACE/discovery",
    kind: "console-flow",
    workflow: "Discovery finding triage",
    rationale: "The Discovery page lists findings and owns claim/dismiss triage with loading, empty, and error states.",
  },
  {
    path: "/api/v1/ephemeral",
    route: "/integrate/api",
    owner: "SURFACE/secrets",
    kind: "api-explorer",
    workflow: "Attestation-gated ephemeral credential request",
    rationale:
      "The Secrets page covers scoped ephemeral API keys; the generic attestation-gated ephemeral credential endpoint remains an API Explorer workflow.",
  },
  {
    path: "/api/v1/ephemeral/{id}/approvals",
    route: "/integrate/api",
    owner: "SURFACE/secrets",
    kind: "api-explorer",
    workflow: "Ephemeral credential approval",
    rationale: "General identity approvals are in the Approvals page; ephemeral credential approval by id is an API Explorer operator action.",
  },
  {
    path: "/api/v1/external-cas/{id}/issue",
    route: "/ca-hierarchy",
    owner: "SURFACE/ca",
    kind: "console-flow",
    workflow: "External CA issuance path discovery",
    rationale: "The CA Hierarchy page surfaces external CA discovery rows and their served issuance paths; direct issue remains an advanced operator action.",
  },
  {
    path: "/api/v1/identities/bulk-revoke",
    route: "/integrate/api",
    owner: "SURFACE/identities",
    kind: "api-explorer",
    workflow: "Criteria-based identity bulk revoke",
    rationale:
      "The Identities page has guarded selected-row bulk revoke via per-identity transitions; criteria-based bulk revoke is covered by the API Explorer.",
  },
  {
    path: "/api/v1/identities/{id}",
    route: "/identities",
    owner: "SURFACE/identities",
    kind: "console-flow",
    workflow: "Identity detail and lifecycle drawer",
    rationale: "The Identities page opens lifecycle detail, delivery evidence, and approval context for selected identities.",
  },
  {
    path: "/api/v1/identities/{id}/transitions",
    route: "/identities",
    owner: "SURFACE/identities",
    kind: "console-flow",
    workflow: "Identity lifecycle transition",
    rationale: "The Identities page drives issue, deploy, renew, revoke, and retire transitions with destructive confirmation and error states.",
  },
  {
    path: "/api/v1/issuers/{id}",
    route: "/integrate/api",
    owner: "SURFACE/ca",
    kind: "api-explorer",
    workflow: "Issuer detail lookup",
    rationale: "Issuer lists and links are shown in CA Hierarchy; arbitrary issuer detail by id is covered by the API Explorer.",
  },
  {
    path: "/api/v1/lifecycle/rotation-runs",
    route: "/operations",
    owner: "SURFACE/lifecycle",
    kind: "console-flow",
    workflow: "Rotation run queue",
    rationale: "The Operations, Dashboard, Identities, and Certificates pages show rotation runs and empty/error states.",
  },
  {
    path: "/api/v1/lifecycle/rotation-runs/{id}",
    route: "/integrate/api",
    owner: "SURFACE/lifecycle",
    kind: "api-explorer",
    workflow: "Rotation run detail lookup",
    rationale: "The console lists recent rotation runs; exact run lookup by id remains an API Explorer support action.",
  },
  {
    path: "/api/v1/notifications/{id}",
    route: "/notifications",
    owner: "SURFACE/notifications",
    kind: "console-flow",
    workflow: "Notification inbox row",
    rationale: "The Notifications page lists rows and drives read/requeue actions with loading, empty, and error states.",
  },
  {
    path: "/api/v1/owners/{id}",
    route: "/integrate/api",
    owner: "SURFACE/owners",
    kind: "api-explorer",
    workflow: "Owner detail/update/delete",
    rationale:
      "The Owners page handles owner lists and create flows; destructive owner update/delete by id is kept in the API Explorer until a guarded owner-admin workflow lands.",
  },
  {
    path: "/api/v1/privacy/subject-exports",
    route: "/integrate/api",
    owner: "SURFACE/privacy",
    kind: "api-explorer",
    workflow: "Privacy subject export",
    rationale: "The Privacy page covers catalog, erasure, and retention; subject portability exports are available through the API Explorer.",
  },
  {
    path: "/api/v1/remediation/playbook-runs",
    route: "/incidents",
    owner: "SURFACE/incidents",
    kind: "console-flow",
    workflow: "Remediation playbook run history",
    rationale: "The Incidents page runs playbooks and displays recent playbook run evidence, including empty/error states.",
  },
  {
    path: "/api/v1/secrets/rotations",
    route: "/integrate/api",
    owner: "SURFACE/secrets",
    kind: "api-explorer",
    workflow: "Rollback-safe static secret rotation",
    rationale:
      "The Secrets page supports manual native-store rotation; scheduled/backend static rotation remains API Explorer/CLI until a dedicated rotation wizard lands.",
  },
  {
    path: "/api/v1/secrets/scans/repositories",
    route: "/secrets",
    owner: "SURFACE/secrets",
    kind: "console-flow",
    workflow: "Repository secret scanning posture",
    rationale: "The Secrets page displays repository scanning posture, provider webhook paths, and empty/error states.",
  },
  {
    path: "/api/v1/secrets/scans/third-party",
    route: "/secrets",
    owner: "SURFACE/secrets",
    kind: "console-flow",
    workflow: "Third-party secret scanning posture",
    rationale: "The Secrets page displays third-party artifact scanning posture and can ingest configured provider artifacts.",
  },
] as const satisfies readonly ApiWorkflowCoverage[];
