package server

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"io"
	"net/http"
	"testing"

	"github.com/jackc/pgx/v5"

	"trstctl.com/trstctl/internal/config"
	"trstctl.com/trstctl/internal/crypto"
	"trstctl.com/trstctl/internal/crypto/mtls"
)

func TestServedEnrollmentTokenPersistsAllowedIdentityRED003(t *testing.T) {
	h := newServedHarness(t, config.Protocols{}, withAgentChannel)
	token := seedScopedToken(t, h.store, h.tenant, "agents:write")

	status, body := secretsReqKey(t, h, http.MethodPost, "/api/v1/agents/enrollment-tokens", token,
		"red-003-agent-token-pin", map[string]any{"allowed_identity": "node-a"})
	if status != http.StatusCreated {
		t.Fatalf("create enrollment token = %d body %s, want 201", status, body)
	}

	var stored string
	err := h.store.WithTenant(context.Background(), h.tenant, func(tx pgx.Tx) error {
		return tx.QueryRow(context.Background(),
			`SELECT allowed_identity FROM agent_bootstrap_tokens WHERE tenant_id = $1`,
			h.tenant).Scan(&stored)
	})
	if err != nil {
		t.Fatalf("read stored allowed identity: %v", err)
	}
	if stored != "node-a" {
		t.Fatalf("stored allowed_identity = %q, want node-a", stored)
	}
}

func TestServedBootstrapHonorsAllowedIdentityWIRE001(t *testing.T) {
	h := newServedHarness(t, config.Protocols{}, withAgentChannel)
	bearer := seedScopedToken(t, h.store, h.tenant, "agents:write")

	mismatchToken := mintServedEnrollmentToken(t, h, bearer, "wire-001-mismatch", "node-a")
	status, body := postServedBootstrap(t, h, mismatchToken, agentCSRWithDNS(t, "node-a", []string{"rogue-node"}))
	if status != http.StatusUnauthorized {
		t.Fatalf("bootstrap with mismatched CSR SAN = %d body %s, want 401", status, body)
	}

	matchToken := mintServedEnrollmentToken(t, h, bearer, "wire-001-match", "node-a")
	status, body = postServedBootstrap(t, h, matchToken, agentCSRWithDNS(t, "node-a", nil))
	if status != http.StatusOK {
		t.Fatalf("bootstrap with matching CSR CN = %d body %s, want 200", status, body)
	}
	var out struct {
		Certificate string `json:"certificate"`
	}
	if err := json.Unmarshal(body, &out); err != nil {
		t.Fatalf("decode bootstrap response: %v", err)
	}
	leaf, err := mtls.FirstCertDER([]byte(out.Certificate))
	if err != nil {
		t.Fatalf("parse issued agent cert: %v", err)
	}
	gotTenant, err := mtls.TenantFromClientCert(leaf)
	if err != nil {
		t.Fatalf("issued agent cert tenant SAN: %v", err)
	}
	if gotTenant != h.tenant {
		t.Fatalf("issued agent cert tenant = %q, want %q", gotTenant, h.tenant)
	}
}

func mintServedEnrollmentToken(t *testing.T, h *servedHarness, bearer, idemKey, allowedIdentity string) string {
	t.Helper()
	status, body := secretsReqKey(t, h, http.MethodPost, "/api/v1/agents/enrollment-tokens", bearer,
		idemKey, map[string]any{"allowed_identity": allowedIdentity})
	if status != http.StatusCreated {
		t.Fatalf("create pinned enrollment token = %d body %s, want 201", status, body)
	}
	var out struct {
		Token string `json:"token"`
	}
	if err := json.Unmarshal(body, &out); err != nil {
		t.Fatalf("decode enrollment token response: %v", err)
	}
	if out.Token == "" {
		t.Fatal("enrollment token response did not include token")
	}
	return out.Token
}

func postServedBootstrap(t *testing.T, h *servedHarness, token string, csr []byte) (int, []byte) {
	t.Helper()
	body, _ := json.Marshal(map[string]string{
		"token": token,
		"csr":   base64.StdEncoding.EncodeToString(csr),
	})
	req, err := http.NewRequest(http.MethodPost, h.ts.URL+"/enroll/bootstrap", bytes.NewReader(body))
	if err != nil {
		t.Fatal(err)
	}
	req.Header.Set("Content-Type", "application/json")
	resp, err := h.ts.Client().Do(req)
	if err != nil {
		t.Fatalf("POST /enroll/bootstrap: %v", err)
	}
	defer func() { _ = resp.Body.Close() }()
	data, _ := io.ReadAll(resp.Body)
	return resp.StatusCode, data
}

func agentCSRWithDNS(t *testing.T, cn string, dns []string) []byte {
	t.Helper()
	key, err := crypto.GenerateLockedKey(crypto.ECDSAP256)
	if err != nil {
		t.Fatalf("generate CSR key: %v", err)
	}
	t.Cleanup(key.Destroy)
	csr, err := crypto.CreateCertificateRequest(crypto.CertificateRequestTemplate{
		CommonName: cn,
		DNSNames:   dns,
	}, key)
	if err != nil {
		t.Fatalf("CreateCertificateRequest: %v", err)
	}
	if !mtls.IsCSR(csr) {
		t.Fatal("generated bytes are not a CSR")
	}
	return csr
}
