# Code generated by clients/sdk/python/scripts/gen_types.py; DO NOT EDIT.
from __future__ import annotations

from typing import Any, TypedDict

AIAnswer = TypedDict(
    'AIAnswer',
    {
        'citations': list[str],
        'grounded': bool,
        'sufficient': bool,
        'text': str,
    },
    total=False,
)

AIQueryRequest = TypedDict(
    'AIQueryRequest',
    {
        'limit': int,
        'question': str,
        'subject': str,
        'surfaces': list[str],
    },
    total=False,
)

AIStatus = TypedDict(
    'AIStatus',
    {
        'egress': str,
        'enabled': bool,
        'endpoint_host': str,
        'mcp_identity': str,
        'mcp_write_tools': bool,
        'model_configured': bool,
        'model_mode': str,
        'model_name': str,
        'provider': str,
        'rate_max': int,
        'rate_window_seconds': int,
        'redaction': str,
        'residual_refusal_gate': bool,
        'runtime': str,
    },
    total=False,
)

APIToken = TypedDict(
    'APIToken',
    {
        'created_at': str,
        'expires_at': str,
        'id': str,
        'revocation_reason': str,
        'revoked_at': str,
        'revoked_by': str,
        'scopes': list[str],
        'subject': str,
        'tenant_id': str,
    },
    total=False,
)

APITokenCreateRequest = TypedDict(
    'APITokenCreateRequest',
    {
        'expires_at': str,
        'scopes': list[str],
        'subject': str,
    },
    total=False,
)

APITokenCreateResponse = TypedDict(
    'APITokenCreateResponse',
    {
        'created_at': str,
        'expires_at': str,
        'id': str,
        'scopes': list[str],
        'subject': str,
        'tenant_id': str,
        'token': str,
    },
    total=False,
)

APITokenList = TypedDict(
    'APITokenList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

APITokenRevokeRequest = TypedDict(
    'APITokenRevokeRequest',
    {
        'reason': str,
    },
    total=False,
)

Agent = TypedDict(
    'Agent',
    {
        'id': str,
        'last_seen_at': str,
        'name': str,
        'status': str,
        'version': str,
    },
    total=False,
)

AgentList = TypedDict(
    'AgentList',
    {
        'agents': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

Approval = TypedDict(
    'Approval',
    {
        'action': str,
        'approvals': int,
        'approver': str,
        'resource': str,
    },
    total=False,
)

ApprovalRequest = TypedDict(
    'ApprovalRequest',
    {
        'action': str,
    },
    total=False,
)

Attestation = TypedDict(
    'Attestation',
    {
        'claims': dict[str, Any],
        'id': str,
        'method': str,
        'selectors': list[str],
        'subject': str,
        'verified_at': str,
    },
    total=False,
)

AttestedSVID = TypedDict(
    'AttestedSVID',
    {
        'attestation': dict[str, Any],
        'certificate_pem': str,
        'credential_id': str,
        'not_after': str,
        'subject': str,
    },
    total=False,
)

AttestedSVIDRequest = TypedDict(
    'AttestedSVIDRequest',
    {
        'method': str,
        'payload_base64': str,
        'public_key_pem': str,
        'ttl_seconds': int,
    },
    total=False,
)

AuditBundle = TypedDict(
    'AuditBundle',
    {
        'bundle': str,
        'format': str,
    },
    total=False,
)

AuditEvent = TypedDict(
    'AuditEvent',
    {
        'actor': dict[str, Any],
        'data': dict[str, Any],
        'hash': str,
        'id': str,
        'sequence': int,
        'tenant_id': str,
        'time': str,
        'type': str,
    },
    total=False,
)

AuditEventList = TypedDict(
    'AuditEventList',
    {
        'count': int,
        'events': list[dict[str, Any]],
    },
    total=False,
)

BreakglassBundle = TypedDict(
    'BreakglassBundle',
    {
        'approvals': list[str],
        'cert_der': str,
        'issued_at': str,
        'reason': str,
        'request_id': str,
        'signature': str,
        'subject': str,
    },
    total=False,
)

BreakglassReconcileRequest = TypedDict(
    'BreakglassReconcileRequest',
    {
        'bundles': list[dict[str, Any]],
    },
    total=False,
)

BreakglassReconcileResponse = TypedDict(
    'BreakglassReconcileResponse',
    {
        'reconciled': int,
    },
    total=False,
)

BrokerAgentIdentity = TypedDict(
    'BrokerAgentIdentity',
    {
        'agent_id': str,
        'attestation': dict[str, Any],
        'certificate_id': str,
        'certificate_pem': str,
        'credential_id': str,
        'node_id': str,
        'not_after': str,
        'scopes': list[str],
        'subject': str,
    },
    total=False,
)

BrokerAgentIdentityRequest = TypedDict(
    'BrokerAgentIdentityRequest',
    {
        'agent_id': str,
        'method': str,
        'payload_base64': str,
        'public_key_pem': str,
        'scopes': list[str],
        'ttl_seconds': int,
    },
    total=False,
)

CAAuthority = TypedDict(
    'CAAuthority',
    {
        'certificate_pem': str,
        'common_name': str,
        'created_at': str,
        'extended_key_usages': list[str],
        'id': str,
        'kind': str,
        'max_path_len': int,
        'not_after': str,
        'parent_id': str,
        'permitted_dns_names': list[str],
        'serial': str,
        'signer_handle': str,
        'status': str,
        'tenant_id': str,
    },
    total=False,
)

CAAuthorityList = TypedDict(
    'CAAuthorityList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

CACeremonyStartRequest = TypedDict(
    'CACeremonyStartRequest',
    {
        'operation': str,
        'parent_id': str,
        'spec': dict[str, Any],
        'threshold': int,
    },
    total=False,
)

CACreateIntermediateRequest = TypedDict(
    'CACreateIntermediateRequest',
    {
        'ceremony_id': str,
        'parent_id': str,
        'spec': dict[str, Any],
    },
    total=False,
)

CACreateRootRequest = TypedDict(
    'CACreateRootRequest',
    {
        'ceremony_id': str,
        'spec': dict[str, Any],
    },
    total=False,
)

CAIssueIntermediateRequest = TypedDict(
    'CAIssueIntermediateRequest',
    {
        'csr_pem': str,
        'spec': dict[str, Any],
    },
    total=False,
)

CAIssueLeafRequest = TypedDict(
    'CAIssueLeafRequest',
    {
        'csr_pem': str,
        'ttl_seconds': int,
    },
    total=False,
)

CAIssuedIntermediate = TypedDict(
    'CAIssuedIntermediate',
    {
        'certificate_pem': str,
        'not_after': str,
        'serial': str,
    },
    total=False,
)

CAIssuedLeaf = TypedDict(
    'CAIssuedLeaf',
    {
        'certificate_pem': str,
        'not_after': str,
        'serial': str,
    },
    total=False,
)

CAKeyCeremony = TypedDict(
    'CAKeyCeremony',
    {
        'approvals': int,
        'created_at': str,
        'id': str,
        'opener': str,
        'purpose': str,
        'status': str,
        'tenant_id': str,
        'threshold': int,
    },
    total=False,
)

CASpec = TypedDict(
    'CASpec',
    {
        'common_name': str,
        'extended_key_usages': list[str],
        'max_path_len': int,
        'permitted_dns_domains': list[str],
        'signature_algorithm': str,
        'ttl_seconds': int,
    },
    total=False,
)

CBOMAsset = TypedDict(
    'CBOMAsset',
    {
        'algorithm': str,
        'cipher': str,
        'id': str,
        'key_bits': int,
        'kind': str,
        'library': str,
        'location': str,
        'migration_generation': str,
        'migration_standard': str,
        'migration_target': str,
        'out_of_policy': bool,
        'protocol': str,
        'quantum_vulnerable': bool,
        'reasons': list[str],
        'strength': str,
    },
    total=False,
)

CBOMInventory = TypedDict(
    'CBOMInventory',
    {
        'items': list[dict[str, Any]],
        'migration_progress': dict[str, Any],
    },
    total=False,
)

CBOMMigrationProgress = TypedDict(
    'CBOMMigrationProgress',
    {
        'out_of_policy_assets': int,
        'percent_migrated': float,
        'post_quantum_ready_assets': int,
        'quantum_vulnerable_assets': int,
        'total_assets': int,
    },
    total=False,
)

CBOMReport = TypedDict(
    'CBOMReport',
    {
        'failed': int,
        'findings': int,
        'out_of_policy': int,
        'quantum_vulnerable': int,
        'sources': int,
        'weak': int,
    },
    total=False,
)

CBOMScan = TypedDict(
    'CBOMScan',
    {
        'migration_progress': dict[str, Any],
        'report': dict[str, Any],
    },
    total=False,
)

CBOMScanRequest = TypedDict(
    'CBOMScanRequest',
    {
        'host_configs': list[str],
        'tls_endpoints': list[str],
    },
    total=False,
)

Certificate = TypedDict(
    'Certificate',
    {
        'created_at': str,
        'deployment_location': str,
        'fingerprint': str,
        'id': str,
        'issuer': str,
        'key_algorithm': str,
        'not_after': str,
        'not_before': str,
        'owner_id': str,
        'revocation_reason': str,
        'revoked_at': str,
        'sans': list[str],
        'serial': str,
        'source': str,
        'status': str,
        'subject': str,
        'tenant_id': str,
    },
    total=False,
)

CertificateIngest = TypedDict(
    'CertificateIngest',
    {
        'deployment_location': str,
        'owner_id': str,
        'pem': str,
        'source': str,
    },
    total=False,
)

CertificateList = TypedDict(
    'CertificateList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

CodeSigningKeylessRequest = TypedDict(
    'CodeSigningKeylessRequest',
    {
        'artifact_type': str,
        'digest': str,
        'fulcio_issuer': str,
        'fulcio_san': str,
        'identity_method': str,
        'identity_payload': str,
    },
    total=False,
)

CodeSigningRequest = TypedDict(
    'CodeSigningRequest',
    {
        'artifact_type': str,
        'digest': str,
        'key_id': str,
    },
    total=False,
)

CodeSigningSignature = TypedDict(
    'CodeSigningSignature',
    {
        'algorithm': str,
        'artifact_type': str,
        'fulcio_issuer': str,
        'fulcio_san': str,
        'key_id': str,
        'public_key_der': str,
        'signature': str,
        'transparency_destination': str,
    },
    total=False,
)

ComplianceEvidencePack = TypedDict(
    'ComplianceEvidencePack',
    {
        'format': str,
        'framework': str,
        'public_key_der': str,
        'signed_export': dict[str, Any],
    },
    total=False,
)

ConnectorCatalog = TypedDict(
    'ConnectorCatalog',
    {
        'items': list[dict[str, Any]],
    },
    total=False,
)

ConnectorCatalogItem = TypedDict(
    'ConnectorCatalogItem',
    {
        'delivery_mode': str,
        'kind': str,
        'name': str,
        'rollback': str,
    },
    total=False,
)

ConnectorDelivery = TypedDict(
    'ConnectorDelivery',
    {
        'attempts': int,
        'connector': str,
        'created_at': str,
        'destination': str,
        'detail': str,
        'fingerprint': str,
        'id': str,
        'idempotency_key': str,
        'identity_id': str,
        'outbox_id': int,
        'reason': str,
        'rollback_ref': str,
        'status': str,
        'target': str,
        'tenant_id': str,
        'updated_at': str,
    },
    total=False,
)

ConnectorDeliveryList = TypedDict(
    'ConnectorDeliveryList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

CredentialRisk = TypedDict(
    'CredentialRisk',
    {
        'components': dict[str, Any],
        'credential_id': str,
        'expires_at': str,
        'exposure': int,
        'kind': str,
        'owner_active': bool,
        'privilege': int,
        'score': float,
        'sensitivity': int,
        'subject': str,
    },
    total=False,
)

CredentialRiskList = TypedDict(
    'CredentialRiskList',
    {
        'credentials': list[dict[str, Any]],
    },
    total=False,
)

DiscoveryFinding = TypedDict(
    'DiscoveryFinding',
    {
        'discovered_at': str,
        'fingerprint': str,
        'id': str,
        'kind': str,
        'metadata': dict[str, Any],
        'provenance': str,
        'ref': str,
        'risk_score': int,
        'run_id': str,
        'source_id': str,
        'tenant_id': str,
    },
    total=False,
)

DiscoveryFindingList = TypedDict(
    'DiscoveryFindingList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

DiscoveryRun = TypedDict(
    'DiscoveryRun',
    {
        'completed_at': str,
        'created_at': str,
        'discovered': int,
        'dry_run': bool,
        'error': str,
        'failed': int,
        'id': str,
        'rejected': int,
        'requested_by': str,
        'schedule_id': str,
        'source_id': str,
        'started_at': str,
        'status': str,
        'targets': int,
        'tenant_id': str,
    },
    total=False,
)

DiscoveryRunList = TypedDict(
    'DiscoveryRunList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

DiscoveryRunRequest = TypedDict(
    'DiscoveryRunRequest',
    {
        'dry_run': bool,
        'schedule_id': str,
        'source_id': str,
    },
    total=False,
)

DiscoverySchedule = TypedDict(
    'DiscoverySchedule',
    {
        'created_at': str,
        'enabled': bool,
        'id': str,
        'interval_seconds': int,
        'name': str,
        'source_id': str,
        'tenant_id': str,
        'updated_at': str,
    },
    total=False,
)

DiscoveryScheduleList = TypedDict(
    'DiscoveryScheduleList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

DiscoveryScheduleRequest = TypedDict(
    'DiscoveryScheduleRequest',
    {
        'enabled': bool,
        'interval_seconds': int,
        'name': str,
        'source_id': str,
    },
    total=False,
)

DiscoverySource = TypedDict(
    'DiscoverySource',
    {
        'config': dict[str, Any],
        'created_at': str,
        'id': str,
        'kind': str,
        'name': str,
        'tenant_id': str,
        'updated_at': str,
    },
    total=False,
)

DiscoverySourceList = TypedDict(
    'DiscoverySourceList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

DiscoverySourceRequest = TypedDict(
    'DiscoverySourceRequest',
    {
        'config': dict[str, Any],
        'kind': str,
        'name': str,
    },
    total=False,
)

DynamicLease = TypedDict(
    'DynamicLease',
    {
        'credential': str,
        'expires_at': str,
        'id': str,
        'issued_at': str,
        'provider': str,
        'role': str,
        'state': str,
    },
    total=False,
)

DynamicLeaseRenewRequest = TypedDict(
    'DynamicLeaseRenewRequest',
    {
        'extend_seconds': int,
    },
    total=False,
)

DynamicLeaseRequest = TypedDict(
    'DynamicLeaseRequest',
    {
        'provider': str,
        'role': str,
        'ttl_seconds': int,
    },
    total=False,
)

EnrollmentToken = TypedDict(
    'EnrollmentToken',
    {
        'enroll_path': str,
        'token': str,
    },
    total=False,
)

EphemeralAPIKey = TypedDict(
    'EphemeralAPIKey',
    {
        'created_at': str,
        'expires_at': str,
        'id': str,
        'scopes': list[str],
        'subject': str,
        'tenant_id': str,
        'token': str,
    },
    total=False,
)

EphemeralAPIKeyRequest = TypedDict(
    'EphemeralAPIKeyRequest',
    {
        'scopes': list[str],
        'subject': str,
        'ttl_seconds': int,
    },
    total=False,
)

EphemeralApproval = TypedDict(
    'EphemeralApproval',
    {
        'action': str,
        'approvals': int,
        'approver': str,
        'resource': str,
    },
    total=False,
)

EphemeralApprovalRequest = TypedDict(
    'EphemeralApprovalRequest',
    {
        'action': str,
    },
    total=False,
)

EphemeralCredential = TypedDict(
    'EphemeralCredential',
    {
        'approvals': int,
        'attestation': dict[str, Any],
        'certificate_id': str,
        'certificate_pem': str,
        'credential_id': str,
        'expires_at': str,
        'not_after': str,
        'request_id': str,
        'required_approvals': int,
        'state': str,
        'subject': str,
    },
    total=False,
)

EphemeralCredentialRequest = TypedDict(
    'EphemeralCredentialRequest',
    {
        'method': str,
        'payload_base64': str,
        'public_key_pem': str,
        'request_id': str,
        'ttl_seconds': int,
    },
    total=False,
)

ExternalCA = TypedDict(
    'ExternalCA',
    {
        'id': str,
        'name': str,
        'status': str,
        'type': str,
    },
    total=False,
)

ExternalCAIssueRequest = TypedDict(
    'ExternalCAIssueRequest',
    {
        'csr_pem': str,
        'dns_names': list[str],
        'profile_name': str,
        'requested_ekus': list[str],
        'ttl_seconds': int,
    },
    total=False,
)

ExternalCAIssuedCertificate = TypedDict(
    'ExternalCAIssuedCertificate',
    {
        'certificate_pem': str,
        'issuer': str,
        'not_after': str,
        'serial': str,
    },
    total=False,
)

ExternalCAList = TypedDict(
    'ExternalCAList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

GraphEdge = TypedDict(
    'GraphEdge',
    {
        'from': str,
        'to': str,
        'type': str,
    },
    total=False,
)

GraphImpact = TypedDict(
    'GraphImpact',
    {
        'affected': list[dict[str, Any]],
        'by_kind': dict[str, Any],
        'node': dict[str, Any],
    },
    total=False,
)

GraphNode = TypedDict(
    'GraphNode',
    {
        'attrs': dict[str, Any],
        'id': str,
        'kind': str,
        'name': str,
    },
    total=False,
)

GraphQueryResult = TypedDict(
    'GraphQueryResult',
    {
        'rows': list[dict[str, Any]],
    },
    total=False,
)

GraphReachable = TypedDict(
    'GraphReachable',
    {
        'from': str,
        'nodes': list[dict[str, Any]],
    },
    total=False,
)

GraphResponse = TypedDict(
    'GraphResponse',
    {
        'edges': list[dict[str, Any]],
        'nodes': list[dict[str, Any]],
    },
    total=False,
)

Identity = TypedDict(
    'Identity',
    {
        'attributes': dict[str, Any],
        'created_at': str,
        'id': str,
        'issuer_id': str,
        'kind': str,
        'name': str,
        'not_after': str,
        'not_before': str,
        'owner_id': str,
        'status': str,
        'tenant_id': str,
    },
    total=False,
)

IdentityList = TypedDict(
    'IdentityList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

IdentityRequest = TypedDict(
    'IdentityRequest',
    {
        'attributes': dict[str, Any],
        'issuer_id': str,
        'kind': str,
        'name': str,
        'owner_id': str,
    },
    total=False,
)

IncidentExecution = TypedDict(
    'IncidentExecution',
    {
        'blast_radius': dict[str, Any],
        'compromised_identity_id': str,
        'connector_delivery': dict[str, Any],
        'connector_delivery_id': str,
        'created_at': str,
        'created_by': str,
        'evidence_bundle': str,
        'evidence_bundle_format': str,
        'failed_targets': list[str],
        'id': str,
        'idempotency_key': str,
        'phase': str,
        'reason': str,
        'replacement_identity': dict[str, Any],
        'replacement_identity_id': str,
        'revocation_status': str,
        'rollback_refs': list[str],
        'status': str,
        'tenant_id': str,
        'updated_at': str,
    },
    total=False,
)

IncidentExecutionList = TypedDict(
    'IncidentExecutionList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

IncidentExecutionRequest = TypedDict(
    'IncidentExecutionRequest',
    {
        'connector': str,
        'delivery_rollback_ref': str,
        'identity_id': str,
        'reason': str,
        'replacement_name': str,
        'target': str,
    },
    total=False,
)

Issuer = TypedDict(
    'Issuer',
    {
        'chain': list[str],
        'chainless': bool,
        'created_at': str,
        'id': str,
        'internal': bool,
        'kind': str,
        'name': str,
        'public_key': str,
        'tenant_id': str,
    },
    total=False,
)

IssuerList = TypedDict(
    'IssuerList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

IssuerRequest = TypedDict(
    'IssuerRequest',
    {
        'chain': list[str],
        'internal': bool,
        'kind': str,
        'name': str,
        'public_key': str,
    },
    total=False,
)

MCPToolCall = TypedDict(
    'MCPToolCall',
    {
        'authority_id': str,
        'csr_pem': str,
        'previous_serial': str,
        'reason': str,
        'subject': str,
        'ttl_seconds': int,
    },
    total=False,
)

MCPToolList = TypedDict(
    'MCPToolList',
    {
        'identity': str,
        'read_only': bool,
        'tools': list[str],
    },
    total=False,
)

MCPToolResult = TypedDict(
    'MCPToolResult',
    {
        'certificate_pem': str,
        'citations': list[str],
        'not_after': str,
        'serial': str,
        'text': str,
        'tool': str,
    },
    total=False,
)

MachineLoginRequest = TypedDict(
    'MachineLoginRequest',
    {
        'credential': str,
        'method': str,
    },
    total=False,
)

MachineLoginResponse = TypedDict(
    'MachineLoginResponse',
    {
        'expires_at': str,
        'method': str,
        'principal': str,
        'scopes': list[str],
        'session_id': str,
    },
    total=False,
)

ManagedKey = TypedDict(
    'ManagedKey',
    {
        'algorithm': str,
        'key_id': str,
        'public_der': str,
        'state': str,
        'version': int,
    },
    total=False,
)

ManagedKeyActionRequest = TypedDict(
    'ManagedKeyActionRequest',
    {
        'key_id': str,
    },
    total=False,
)

ManagedKeyGenerateRequest = TypedDict(
    'ManagedKeyGenerateRequest',
    {
        'algorithm': str,
    },
    total=False,
)

Member = TypedDict(
    'Member',
    {
        'created_at': str,
        'display_name': str,
        'email': str,
        'offboard_reason': str,
        'offboarded_at': str,
        'offboarded_by': str,
        'roles': list[str],
        'source': str,
        'status': str,
        'subject': str,
        'tenant_id': str,
        'updated_at': str,
    },
    total=False,
)

MemberList = TypedDict(
    'MemberList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

MemberRequest = TypedDict(
    'MemberRequest',
    {
        'display_name': str,
        'email': str,
        'roles': list[str],
        'source': str,
    },
    total=False,
)

OIDCMappingStatus = TypedDict(
    'OIDCMappingStatus',
    {
        'allow_default_tenant': bool,
        'claim_is_tenant': bool,
        'default_roles': list[str],
        'default_tenant': str,
        'enabled': bool,
        'groups_claim': str,
        'tenant_claim': str,
        'tenant_mappings': list[dict[str, Any]],
    },
    total=False,
)

OIDCTenantMapping = TypedDict(
    'OIDCTenantMapping',
    {
        'claim': str,
        'group': str,
        'roles': list[str],
        'subject': str,
        'tenant_id': str,
    },
    total=False,
)

OffboardMemberRequest = TypedDict(
    'OffboardMemberRequest',
    {
        'reason': str,
    },
    total=False,
)

OffboardMemberResponse = TypedDict(
    'OffboardMemberResponse',
    {
        'member': dict[str, Any],
        'revoked_token_count': int,
        'rotation_evidence': str,
    },
    total=False,
)

OutboxCircuit = TypedDict(
    'OutboxCircuit',
    {
        'destination': str,
        'failures': int,
        'last_error': str,
        'open_until': str,
        'state': str,
        'tenant_id': str,
        'updated_at': str,
    },
    total=False,
)

OutboxCircuitList = TypedDict(
    'OutboxCircuitList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

Owner = TypedDict(
    'Owner',
    {
        'created_at': str,
        'email': str,
        'id': str,
        'kind': str,
        'name': str,
        'tenant_id': str,
    },
    total=False,
)

OwnerList = TypedDict(
    'OwnerList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

OwnerRequest = TypedDict(
    'OwnerRequest',
    {
        'email': str,
        'kind': str,
        'name': str,
    },
    total=False,
)

PAMPostgresCredential = TypedDict(
    'PAMPostgresCredential',
    {
        'dsn': str,
        'username': str,
    },
    total=False,
)

PAMSSHCredential = TypedDict(
    'PAMSSHCredential',
    {
        'certificate': str,
        'key_id': str,
        'principal': str,
        'serial': int,
        'valid_before': str,
    },
    total=False,
)

PAMSession = TypedDict(
    'PAMSession',
    {
        'attestation': dict[str, Any],
        'audit': dict[str, Any],
        'ended_at': str,
        'expires_at': str,
        'id': str,
        'postgres': dict[str, Any],
        'reason': str,
        'requested_by': str,
        'role': str,
        'ssh': dict[str, Any],
        'started_at': str,
        'status': str,
        'subject': str,
        'target_id': str,
        'target_type': str,
    },
    total=False,
)

PAMSessionList = TypedDict(
    'PAMSessionList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

PAMSessionRequest = TypedDict(
    'PAMSessionRequest',
    {
        'method': str,
        'payload_base64': str,
        'reason': str,
        'role': str,
        'ssh_principal': str,
        'ssh_public_key': str,
        'target_id': str,
        'target_type': str,
        'ttl_seconds': int,
    },
    total=False,
)

PKISecret = TypedDict(
    'PKISecret',
    {
        'certificate': str,
        'common_name': str,
        'private_key': str,
        'serial': str,
    },
    total=False,
)

PKISecretRequest = TypedDict(
    'PKISecretRequest',
    {
        'common_name': str,
        'ttl_seconds': int,
    },
    total=False,
)

PQCMigration = TypedDict(
    'PQCMigration',
    {
        'effective_algorithm': str,
        'migration_progress': dict[str, Any],
        'protocol': str,
        'queued': int,
        'queued_at': str,
        'rollback_configured': bool,
        'run_id': str,
        'target_algorithm': str,
    },
    total=False,
)

PQCMigrationRequest = TypedDict(
    'PQCMigrationRequest',
    {
        'asset_ids': list[str],
        'protocol': str,
        'rollback_on_failure': bool,
        'target_algorithm': str,
    },
    total=False,
)

PQCMigrationRollback = TypedDict(
    'PQCMigrationRollback',
    {
        'migration_progress': dict[str, Any],
        'queued': int,
        'queued_at': str,
        'reason': str,
        'run_id': str,
    },
    total=False,
)

PQCMigrationRollbackRequest = TypedDict(
    'PQCMigrationRollbackRequest',
    {
        'asset_ids': list[str],
        'reason': str,
    },
    total=False,
)

PrivacyCatalog = TypedDict(
    'PrivacyCatalog',
    {
        'items': list[dict[str, Any]],
    },
    total=False,
)

PrivacyCatalogEntry = TypedDict(
    'PrivacyCatalogEntry',
    {
        'category': str,
        'erasure': str,
        'id': str,
        'location': str,
        'owner': str,
        'purpose': str,
        'retention_class': str,
    },
    total=False,
)

PrivacyErasureSelectors = TypedDict(
    'PrivacyErasureSelectors',
    {
        'attestation_ids': list[str],
        'certificate_fingerprints': list[str],
        'identity_ids': list[str],
        'owner_ids': list[str],
        'ssh_key_ids': list[str],
    },
    total=False,
)

PrivacyRetentionCutoffs = TypedDict(
    'PrivacyRetentionCutoffs',
    {
        'access_terminal_before': str,
        'agent_stale_before': str,
        'approval_actor_before': str,
        'attestation_evidence_before': str,
        'certificate_terminal_before': str,
        'identity_terminal_before': str,
        'owner_inactive_before': str,
        'profile_actor_before': str,
        'ssh_stale_before': str,
    },
    total=False,
)

PrivacyRetentionRun = TypedDict(
    'PrivacyRetentionRun',
    {
        'counts': dict[str, Any],
        'cutoffs': dict[str, Any],
        'enforced_at': str,
        'requested_by_ref': str,
        'run_id': str,
    },
    total=False,
)

PrivacyRetentionRunList = TypedDict(
    'PrivacyRetentionRunList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

PrivacySubjectErasure = TypedDict(
    'PrivacySubjectErasure',
    {
        'counts': dict[str, Any],
        'erased_at': str,
        'reason': str,
        'requested_by_ref': str,
        'selectors': dict[str, Any],
        'subject_ref': str,
    },
    total=False,
)

PrivacySubjectErasureList = TypedDict(
    'PrivacySubjectErasureList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

PrivacySubjectErasureRequest = TypedDict(
    'PrivacySubjectErasureRequest',
    {
        'reason': str,
        'subject': str,
    },
    total=False,
)

PrivacySubjectExport = TypedDict(
    'PrivacySubjectExport',
    {
        'api_tokens': list[dict[str, Any]],
        'approvals': list[dict[str, Any]],
        'attestations': list[dict[str, Any]],
        'certificates': list[dict[str, Any]],
        'counts': dict[str, Any],
        'generated_at': str,
        'identities': list[dict[str, Any]],
        'owners': list[dict[str, Any]],
        'ssh_keys': list[dict[str, Any]],
        'subject': str,
        'subject_ref': str,
        'tenant_id': str,
        'tenant_members': list[dict[str, Any]],
    },
    total=False,
)

PrivacySubjectExportRequest = TypedDict(
    'PrivacySubjectExportRequest',
    {
        'subject': str,
    },
    total=False,
)

Problem = TypedDict(
    'Problem',
    {
        'detail': str,
        'instance': str,
        'status': int,
        'title': str,
        'type': str,
    },
    total=False,
)

Profile = TypedDict(
    'Profile',
    {
        'active': bool,
        'created_by': str,
        'id': str,
        'name': str,
        'spec': dict[str, Any],
        'version': int,
    },
    total=False,
)

ProfileList = TypedDict(
    'ProfileList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

ProfileRequest = TypedDict(
    'ProfileRequest',
    {
        'name': str,
        'spec': dict[str, Any],
    },
    total=False,
)

RCARequest = TypedDict(
    'RCARequest',
    {
        'question': str,
        'subject': str,
    },
    total=False,
)

RiskComponents = TypedDict(
    'RiskComponents',
    {
        'age': float,
        'exposure': float,
        'owner': float,
        'privilege': float,
        'rotation': float,
        'sensitivity': float,
    },
    total=False,
)

Role = TypedDict(
    'Role',
    {
        'name': str,
        'permissions': list[str],
    },
    total=False,
)

RoleList = TypedDict(
    'RoleList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

RotationRun = TypedDict(
    'RotationRun',
    {
        'completed_at': str,
        'created_at': str,
        'error': str,
        'id': str,
        'idempotency_key': str,
        'identity_id': str,
        'outbox_id': int,
        'predecessor_fingerprint': str,
        'reason': str,
        'rollback_ref': str,
        'status': str,
        'successor_fingerprint': str,
        'tenant_id': str,
        'trigger': str,
        'updated_at': str,
    },
    total=False,
)

RotationRunList = TypedDict(
    'RotationRunList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

SecretImportRequest = TypedDict(
    'SecretImportRequest',
    {
        'prefix': str,
        'values': dict[str, Any],
    },
    total=False,
)

SecretMeta = TypedDict(
    'SecretMeta',
    {
        'created_at': str,
        'name': str,
        'updated_at': str,
        'version': int,
    },
    total=False,
)

SecretMetaList = TypedDict(
    'SecretMetaList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

SecretRecoverRequest = TypedDict(
    'SecretRecoverRequest',
    {
        'at': str,
    },
    total=False,
)

SecretRequest = TypedDict(
    'SecretRequest',
    {
        'name': str,
        'value': str,
    },
    total=False,
)

SecretRotation = TypedDict(
    'SecretRotation',
    {
        'completed': bool,
        'error': str,
        'failed_phase': str,
        'key': str,
        'new_ref': str,
        'old_ref': str,
        'rollback_attempted': bool,
        'rollback_error': str,
        'rollback_failed': bool,
        'rolled_back': bool,
    },
    total=False,
)

SecretRotationRequest = TypedDict(
    'SecretRotationRequest',
    {
        'key': str,
        'old_ref': str,
        'provider': str,
    },
    total=False,
)

SecretScan = TypedDict(
    'SecretScan',
    {
        'engine_version': str,
        'findings': list[dict[str, Any]],
        'findings_count': int,
        'rules_active': int,
        'run_id': str,
        'scanner': str,
    },
    total=False,
)

SecretScanFinding = TypedDict(
    'SecretScanFinding',
    {
        'credential_ref': str,
        'file': str,
        'line': int,
        'rule_id': str,
    },
    total=False,
)

SecretScanRequest = TypedDict(
    'SecretScanRequest',
    {
        'path': str,
    },
    total=False,
)

SecretSync = TypedDict(
    'SecretSync',
    {
        'delivered': bool,
        'enqueued': bool,
        'name': str,
        'remote_key': str,
        'target': str,
    },
    total=False,
)

SecretSyncRequest = TypedDict(
    'SecretSyncRequest',
    {
        'name': str,
        'remote_key': str,
        'target': str,
    },
    total=False,
)

SecretValue = TypedDict(
    'SecretValue',
    {
        'name': str,
        'value': str,
        'version': int,
    },
    total=False,
)

ShareRedeemRequest = TypedDict(
    'ShareRedeemRequest',
    {
        'token': str,
    },
    total=False,
)

ShareRequest = TypedDict(
    'ShareRequest',
    {
        'ttl_seconds': int,
        'value': str,
    },
    total=False,
)

ShareToken = TypedDict(
    'ShareToken',
    {
        'expires_at': str,
        'token': str,
    },
    total=False,
)

ShareValue = TypedDict(
    'ShareValue',
    {
        'value': str,
    },
    total=False,
)

TransitCiphertext = TypedDict(
    'TransitCiphertext',
    {
        'ciphertext': str,
        'version': int,
    },
    total=False,
)

TransitDecryptRequest = TypedDict(
    'TransitDecryptRequest',
    {
        'aad': str,
        'ciphertext': str,
        'key': str,
    },
    total=False,
)

TransitEncryptRequest = TypedDict(
    'TransitEncryptRequest',
    {
        'aad': str,
        'key': str,
        'plaintext': str,
    },
    total=False,
)

TransitHMAC = TypedDict(
    'TransitHMAC',
    {
        'hmac': str,
    },
    total=False,
)

TransitHMACRequest = TypedDict(
    'TransitHMACRequest',
    {
        'data': str,
        'key': str,
    },
    total=False,
)

TransitKey = TypedDict(
    'TransitKey',
    {
        'kind': str,
        'name': str,
        'version': int,
    },
    total=False,
)

TransitKeyRequest = TypedDict(
    'TransitKeyRequest',
    {
        'kind': str,
        'name': str,
    },
    total=False,
)

TransitPlaintext = TypedDict(
    'TransitPlaintext',
    {
        'plaintext': str,
    },
    total=False,
)

TransitRewrapRequest = TypedDict(
    'TransitRewrapRequest',
    {
        'aad': str,
        'ciphertext': str,
        'key': str,
    },
    total=False,
)

TransitRotateRequest = TypedDict(
    'TransitRotateRequest',
    {
        'name': str,
    },
    total=False,
)

TransitSignRequest = TypedDict(
    'TransitSignRequest',
    {
        'key': str,
        'message': str,
    },
    total=False,
)

TransitSignature = TypedDict(
    'TransitSignature',
    {
        'public_der': str,
        'signature': str,
    },
    total=False,
)

TransitVerify = TypedDict(
    'TransitVerify',
    {
        'valid': bool,
    },
    total=False,
)

TransitVerifyRequest = TypedDict(
    'TransitVerifyRequest',
    {
        'message': str,
        'public_der': str,
        'signature': str,
    },
    total=False,
)

TransitionRequest = TypedDict(
    'TransitionRequest',
    {
        'reason': str,
        'to': str,
    },
    total=False,
)

Schema = dict[str, Any]
