# Code generated by clients/sdk/python/scripts/gen_types.py; DO NOT EDIT.
from __future__ import annotations

from typing import Any, TypedDict

ACMEDNS01ProviderCatalog = TypedDict(
    'ACMEDNS01ProviderCatalog',
    {
        'items': list[dict[str, Any]],
    },
    total=False,
)

ACMEDNS01ProviderCatalogItem = TypedDict(
    'ACMEDNS01ProviderCatalogItem',
    {
        'capabilities': list[str],
        'conformance': str,
        'credential_reference_fields': list[str],
        'display_name': str,
        'kind': str,
        'name': str,
        'notes': str,
        'propagation_preflight': bool,
        'provider_package': str,
        'secret_fields': list[str],
        'served': bool,
    },
    total=False,
)

AIAnswer = TypedDict(
    'AIAnswer',
    {
        'citations': list[str],
        'grounded': bool,
        'sufficient': bool,
        'text': str,
    },
    total=False,
)

AIQueryRequest = TypedDict(
    'AIQueryRequest',
    {
        'limit': int,
        'question': str,
        'subject': str,
        'surfaces': list[str],
    },
    total=False,
)

AIStatus = TypedDict(
    'AIStatus',
    {
        'egress': str,
        'enabled': bool,
        'endpoint_host': str,
        'mcp_identity': str,
        'mcp_write_tools': bool,
        'model_configured': bool,
        'model_mode': str,
        'model_name': str,
        'provider': str,
        'rate_max': int,
        'rate_window_seconds': int,
        'redaction': str,
        'residual_refusal_gate': bool,
        'runtime': str,
    },
    total=False,
)

APIToken = TypedDict(
    'APIToken',
    {
        'created_at': str,
        'expires_at': str,
        'id': str,
        'revocation_reason': str,
        'revoked_at': str,
        'revoked_by': str,
        'scopes': list[str],
        'subject': str,
        'tenant_id': str,
    },
    total=False,
)

APITokenCreateRequest = TypedDict(
    'APITokenCreateRequest',
    {
        'expires_at': str,
        'scopes': list[str],
        'subject': str,
    },
    total=False,
)

APITokenCreateResponse = TypedDict(
    'APITokenCreateResponse',
    {
        'created_at': str,
        'expires_at': str,
        'id': str,
        'scopes': list[str],
        'subject': str,
        'tenant_id': str,
        'token': str,
    },
    total=False,
)

APITokenList = TypedDict(
    'APITokenList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

APITokenRevokeRequest = TypedDict(
    'APITokenRevokeRequest',
    {
        'reason': str,
    },
    total=False,
)

Agent = TypedDict(
    'Agent',
    {
        'discovery_capabilities': list[dict[str, Any]],
        'id': str,
        'inventory_report_path': str,
        'last_seen_at': str,
        'name': str,
        'status': str,
        'version': str,
    },
    total=False,
)

AgentCertRevocation = TypedDict(
    'AgentCertRevocation',
    {
        'agent': str,
        'agent_id': str,
        'fingerprint': str,
        'reason': str,
        'revoked_at': str,
        'serial': str,
    },
    total=False,
)

AgentCertRevocationRequest = TypedDict(
    'AgentCertRevocationRequest',
    {
        'agent': str,
        'fingerprint': str,
        'reason': str,
        'serial': str,
    },
    total=False,
)

AgentDiscoveryCapability = TypedDict(
    'AgentDiscoveryCapability',
    {
        'label': str,
        'metadata_only': bool,
        'private_key_bytes': bool,
        'reported_over': str,
        'source_kind': str,
    },
    total=False,
)

AgentList = TypedDict(
    'AgentList',
    {
        'agents': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

AlertRecipient = TypedDict(
    'AlertRecipient',
    {
        'display_name': str,
        'email': str,
        'kind': str,
        'roles': list[str],
        'subject': str,
    },
    total=False,
)

Approval = TypedDict(
    'Approval',
    {
        'action': str,
        'approvals': int,
        'approver': str,
        'resource': str,
    },
    total=False,
)

ApprovalRequest = TypedDict(
    'ApprovalRequest',
    {
        'action': str,
    },
    total=False,
)

Attestation = TypedDict(
    'Attestation',
    {
        'claims': dict[str, Any],
        'id': str,
        'method': str,
        'selectors': list[str],
        'subject': str,
        'verified_at': str,
    },
    total=False,
)

AttestedSVID = TypedDict(
    'AttestedSVID',
    {
        'attestation': dict[str, Any],
        'certificate_pem': str,
        'credential_id': str,
        'not_after': str,
        'subject': str,
    },
    total=False,
)

AttestedSVIDRequest = TypedDict(
    'AttestedSVIDRequest',
    {
        'method': str,
        'payload_base64': str,
        'public_key_pem': str,
        'ttl_seconds': int,
    },
    total=False,
)

AuditBundle = TypedDict(
    'AuditBundle',
    {
        'bundle': str,
        'format': str,
    },
    total=False,
)

AuditEvent = TypedDict(
    'AuditEvent',
    {
        'actor': dict[str, Any],
        'data': dict[str, Any],
        'hash': str,
        'id': str,
        'sequence': int,
        'tenant_id': str,
        'time': str,
        'type': str,
    },
    total=False,
)

AuditEventList = TypedDict(
    'AuditEventList',
    {
        'count': int,
        'events': list[dict[str, Any]],
    },
    total=False,
)

BreakglassBundle = TypedDict(
    'BreakglassBundle',
    {
        'approvals': list[str],
        'cert_der': str,
        'issued_at': str,
        'reason': str,
        'request_id': str,
        'signature': str,
        'subject': str,
    },
    total=False,
)

BreakglassReconcileRequest = TypedDict(
    'BreakglassReconcileRequest',
    {
        'bundles': list[dict[str, Any]],
    },
    total=False,
)

BreakglassReconcileResponse = TypedDict(
    'BreakglassReconcileResponse',
    {
        'reconciled': int,
    },
    total=False,
)

BrokerAgentIdentity = TypedDict(
    'BrokerAgentIdentity',
    {
        'agent_id': str,
        'attestation': dict[str, Any],
        'certificate_id': str,
        'certificate_pem': str,
        'credential_id': str,
        'node_id': str,
        'not_after': str,
        'scopes': list[str],
        'subject': str,
    },
    total=False,
)

BrokerAgentIdentityRequest = TypedDict(
    'BrokerAgentIdentityRequest',
    {
        'agent_id': str,
        'method': str,
        'payload_base64': str,
        'public_key_pem': str,
        'scopes': list[str],
        'ttl_seconds': int,
    },
    total=False,
)

BulkRevokeItem = TypedDict(
    'BulkRevokeItem',
    {
        'error': str,
        'id': str,
        'status': str,
    },
    total=False,
)

BulkRevokeRequest = TypedDict(
    'BulkRevokeRequest',
    {
        'certificate_ids': list[str],
        'identity_ids': list[str],
        'ids': list[str],
        'issuer_id': str,
        'kind': str,
        'owner_id': str,
        'reason': str,
        'status': str,
    },
    total=False,
)

BulkRevokeResult = TypedDict(
    'BulkRevokeResult',
    {
        'items': list[dict[str, Any]],
        'total_failed': int,
        'total_matched': int,
        'total_revoked': int,
        'total_skipped': int,
    },
    total=False,
)

CAAuthority = TypedDict(
    'CAAuthority',
    {
        'certificate_pem': str,
        'common_name': str,
        'created_at': str,
        'extended_key_usages': list[str],
        'id': str,
        'kind': str,
        'max_path_len': int,
        'not_after': str,
        'parent_id': str,
        'permitted_dns_names': list[str],
        'serial': str,
        'signer_handle': str,
        'status': str,
        'tenant_id': str,
    },
    total=False,
)

CAAuthorityList = TypedDict(
    'CAAuthorityList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

CACeremonyStartRequest = TypedDict(
    'CACeremonyStartRequest',
    {
        'certificate_pem': str,
        'csr_pem': str,
        'operation': str,
        'parent_id': str,
        'signer_handle': str,
        'spec': dict[str, Any],
        'threshold': int,
    },
    total=False,
)

CACreateIntermediateRequest = TypedDict(
    'CACreateIntermediateRequest',
    {
        'ceremony_id': str,
        'parent_id': str,
        'spec': dict[str, Any],
    },
    total=False,
)

CACreateOfflineIntermediateCSRRequest = TypedDict(
    'CACreateOfflineIntermediateCSRRequest',
    {
        'ceremony_id': str,
        'spec': dict[str, Any],
    },
    total=False,
)

CACreateRootRequest = TypedDict(
    'CACreateRootRequest',
    {
        'ceremony_id': str,
        'spec': dict[str, Any],
    },
    total=False,
)

CADiscoveryInventory = TypedDict(
    'CADiscoveryInventory',
    {
        'items': list[dict[str, Any]],
        'summary': dict[str, Any],
    },
    total=False,
)

CADiscoveryItem = TypedDict(
    'CADiscoveryItem',
    {
        'discovery_methods': list[str],
        'id': str,
        'import_path': str,
        'inventory_path': str,
        'issuance_path': str,
        'managed': bool,
        'name': str,
        'not_after': str,
        'parent_id': str,
        'scope': str,
        'serial': str,
        'source': str,
        'source_id': str,
        'status': str,
        'type': str,
    },
    total=False,
)

CADiscoverySummary = TypedDict(
    'CADiscoverySummary',
    {
        'authority_count': int,
        'external_registry_count': int,
        'private_count': int,
        'public_count': int,
    },
    total=False,
)

CAImportExistingRequest = TypedDict(
    'CAImportExistingRequest',
    {
        'ceremony_id': str,
        'certificate_pem': str,
        'signer_handle': str,
        'spec': dict[str, Any],
    },
    total=False,
)

CAImportOfflineIntermediateRequest = TypedDict(
    'CAImportOfflineIntermediateRequest',
    {
        'ceremony_id': str,
        'certificate_pem': str,
        'spec': dict[str, Any],
    },
    total=False,
)

CAImportOfflineRootRequest = TypedDict(
    'CAImportOfflineRootRequest',
    {
        'ceremony_id': str,
        'certificate_pem': str,
        'spec': dict[str, Any],
    },
    total=False,
)

CAIntermediateCSR = TypedDict(
    'CAIntermediateCSR',
    {
        'ceremony_id': str,
        'csr_pem': str,
        'parent_id': str,
        'signer_handle': str,
    },
    total=False,
)

CAIssueIntermediateRequest = TypedDict(
    'CAIssueIntermediateRequest',
    {
        'ceremony_id': str,
        'csr_pem': str,
        'spec': dict[str, Any],
    },
    total=False,
)

CAIssueLeafRequest = TypedDict(
    'CAIssueLeafRequest',
    {
        'csr_pem': str,
        'ttl_seconds': int,
    },
    total=False,
)

CAIssuedIntermediate = TypedDict(
    'CAIssuedIntermediate',
    {
        'certificate_pem': str,
        'not_after': str,
        'serial': str,
    },
    total=False,
)

CAIssuedLeaf = TypedDict(
    'CAIssuedLeaf',
    {
        'certificate_pem': str,
        'not_after': str,
        'serial': str,
    },
    total=False,
)

CAKeyCeremony = TypedDict(
    'CAKeyCeremony',
    {
        'approvals': int,
        'created_at': str,
        'id': str,
        'opener': str,
        'purpose': str,
        'status': str,
        'tenant_id': str,
        'threshold': int,
    },
    total=False,
)

CASpec = TypedDict(
    'CASpec',
    {
        'common_name': str,
        'extended_key_usages': list[str],
        'max_path_len': int,
        'permitted_dns_domains': list[str],
        'signature_algorithm': str,
        'ttl_seconds': int,
    },
    total=False,
)

CBOMAsset = TypedDict(
    'CBOMAsset',
    {
        'algorithm': str,
        'cipher': str,
        'id': str,
        'key_bits': int,
        'kind': str,
        'library': str,
        'location': str,
        'migration_generation': str,
        'migration_standard': str,
        'migration_target': str,
        'out_of_policy': bool,
        'protocol': str,
        'quantum_vulnerable': bool,
        'reasons': list[str],
        'strength': str,
    },
    total=False,
)

CBOMInventory = TypedDict(
    'CBOMInventory',
    {
        'items': list[dict[str, Any]],
        'migration_progress': dict[str, Any],
    },
    total=False,
)

CBOMMigrationProgress = TypedDict(
    'CBOMMigrationProgress',
    {
        'out_of_policy_assets': int,
        'percent_migrated': float,
        'post_quantum_ready_assets': int,
        'quantum_vulnerable_assets': int,
        'total_assets': int,
    },
    total=False,
)

CBOMReport = TypedDict(
    'CBOMReport',
    {
        'failed': int,
        'findings': int,
        'out_of_policy': int,
        'quantum_vulnerable': int,
        'sources': int,
        'weak': int,
    },
    total=False,
)

CBOMScan = TypedDict(
    'CBOMScan',
    {
        'migration_progress': dict[str, Any],
        'report': dict[str, Any],
    },
    total=False,
)

CBOMScanRequest = TypedDict(
    'CBOMScanRequest',
    {
        'host_configs': list[str],
        'tls_endpoints': list[str],
    },
    total=False,
)

Certificate = TypedDict(
    'Certificate',
    {
        'created_at': str,
        'deployment_location': str,
        'fingerprint': str,
        'id': str,
        'issuer': str,
        'key_algorithm': str,
        'not_after': str,
        'not_before': str,
        'owner_id': str,
        'revocation_reason': str,
        'revoked_at': str,
        'sans': list[str],
        'serial': str,
        'source': str,
        'status': str,
        'subject': str,
        'tenant_id': str,
    },
    total=False,
)

CertificateExpiryBucket = TypedDict(
    'CertificateExpiryBucket',
    {
        'count': int,
        'name': str,
    },
    total=False,
)

CertificateHealthDashboard = TypedDict(
    'CertificateHealthDashboard',
    {
        'expiring': list[dict[str, Any]],
        'expiring_path': str,
        'expiry_buckets': list[dict[str, Any]],
        'generated_at': str,
        'inventory_path': str,
        'source_breakdown': list[dict[str, Any]],
        'summary': dict[str, Any],
    },
    total=False,
)

CertificateHealthItem = TypedDict(
    'CertificateHealthItem',
    {
        'days_remaining': int,
        'deployment_location': str,
        'externally_issued': bool,
        'fingerprint': str,
        'id': str,
        'not_after': str,
        'source': str,
        'status': str,
        'subject': str,
    },
    total=False,
)

CertificateHealthSummary = TypedDict(
    'CertificateHealthSummary',
    {
        'active': int,
        'discovered_count': int,
        'expired': int,
        'expiring_30d': int,
        'expiring_7d': int,
        'expiring_90d': int,
        'external_source_count': int,
        'health': str,
        'imported_count': int,
        'revoked': int,
        'superseded': int,
        'total': int,
        'unknown_expiry_count': int,
    },
    total=False,
)

CertificateIngest = TypedDict(
    'CertificateIngest',
    {
        'deployment_location': str,
        'owner_id': str,
        'pem': str,
        'source': str,
    },
    total=False,
)

CertificateList = TypedDict(
    'CertificateList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

CertificateSourceHealth = TypedDict(
    'CertificateSourceHealth',
    {
        'count': int,
        'expired': int,
        'expiring_30d': int,
        'external': bool,
        'source': str,
    },
    total=False,
)

CodeSigningKeylessRequest = TypedDict(
    'CodeSigningKeylessRequest',
    {
        'artifact_type': str,
        'digest': str,
        'fulcio_issuer': str,
        'fulcio_san': str,
        'identity_method': str,
        'identity_payload': str,
    },
    total=False,
)

CodeSigningRequest = TypedDict(
    'CodeSigningRequest',
    {
        'artifact_type': str,
        'digest': str,
        'key_id': str,
    },
    total=False,
)

CodeSigningSignature = TypedDict(
    'CodeSigningSignature',
    {
        'algorithm': str,
        'artifact_type': str,
        'fulcio_issuer': str,
        'fulcio_san': str,
        'key_id': str,
        'public_key_der': str,
        'signature': str,
        'transparency_destination': str,
    },
    total=False,
)

ComplianceEvidencePack = TypedDict(
    'ComplianceEvidencePack',
    {
        'format': str,
        'framework': str,
        'public_key_der': str,
        'signed_export': dict[str, Any],
    },
    total=False,
)

ComplianceInventoryReport = TypedDict(
    'ComplianceInventoryReport',
    {
        'capability': str,
        'evidence_refs': list[str],
        'frameworks': list[str],
        'generated_at': str,
        'report_types': list[str],
        'routes': list[str],
        'schedules': list[dict[str, Any]],
        'summary': dict[str, Any],
    },
    total=False,
)

ComplianceInventorySummary = TypedDict(
    'ComplianceInventorySummary',
    {
        'certificates': int,
        'crypto_assets': int,
        'discovery_schedules': int,
        'enabled_report_schedules': int,
        'frameworks_supported': int,
        'inventory_rows': int,
        'report_schedules': int,
        'report_types_supported': int,
    },
    total=False,
)

ComplianceReportSchedule = TypedDict(
    'ComplianceReportSchedule',
    {
        'created_at': str,
        'delivery': str,
        'enabled': bool,
        'framework': str,
        'id': str,
        'interval_seconds': int,
        'name': str,
        'next_run_at': str,
        'recipient_ref': str,
        'report_type': str,
        'tenant_id': str,
        'updated_at': str,
    },
    total=False,
)

ComplianceReportScheduleList = TypedDict(
    'ComplianceReportScheduleList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

ComplianceReportScheduleRequest = TypedDict(
    'ComplianceReportScheduleRequest',
    {
        'delivery': str,
        'enabled': bool,
        'framework': str,
        'interval_seconds': int,
        'name': str,
        'recipient_ref': str,
        'report_type': str,
    },
    total=False,
)

ConnectorCatalog = TypedDict(
    'ConnectorCatalog',
    {
        'items': list[dict[str, Any]],
    },
    total=False,
)

ConnectorCatalogItem = TypedDict(
    'ConnectorCatalogItem',
    {
        'delivery_mode': str,
        'kind': str,
        'name': str,
        'rollback': str,
    },
    total=False,
)

ConnectorDelivery = TypedDict(
    'ConnectorDelivery',
    {
        'attempts': int,
        'connector': str,
        'created_at': str,
        'destination': str,
        'detail': str,
        'fingerprint': str,
        'id': str,
        'idempotency_key': str,
        'identity_id': str,
        'outbox_id': int,
        'reason': str,
        'rollback_ref': str,
        'status': str,
        'target': str,
        'tenant_id': str,
        'updated_at': str,
    },
    total=False,
)

ConnectorDeliveryList = TypedDict(
    'ConnectorDeliveryList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

ConnectorTargetActionRequest = TypedDict(
    'ConnectorTargetActionRequest',
    {
        'identity_id': str,
        'reason': str,
    },
    total=False,
)

ContextualRiskPriorities = TypedDict(
    'ContextualRiskPriorities',
    {
        'capability': str,
        'coverage': list[str],
        'generated_at': str,
        'priorities': list[dict[str, Any]],
        'summary': dict[str, Any],
    },
    total=False,
)

ContextualRiskPriority = TypedDict(
    'ContextualRiskPriority',
    {
        'base_score': float,
        'blast_radius': int,
        'components': dict[str, Any],
        'contextual_score': float,
        'credential_blast_radius': int,
        'credential_id': str,
        'crypto_asset_blast_radius': int,
        'evidence_refs': list[str],
        'expires_at': str,
        'kind': str,
        'owner_active': bool,
        'priority_reasons': list[str],
        'privilege': int,
        'rank': int,
        'recommended_action': str,
        'resource_blast_radius': int,
        'sensitivity': int,
        'severity': str,
        'subject': str,
        'weak_crypto_context': int,
        'workload_blast_radius': int,
    },
    total=False,
)

ContextualRiskSummary = TypedDict(
    'ContextualRiskSummary',
    {
        'critical': int,
        'high': int,
        'high_blast_radius': int,
        'low': int,
        'medium': int,
        'near_expiry': int,
        'orphaned': int,
        'priorities': int,
        'recommendations': int,
        'total_analyzed': int,
        'weak_crypto_context': int,
    },
    total=False,
)

CredentialRisk = TypedDict(
    'CredentialRisk',
    {
        'components': dict[str, Any],
        'credential_id': str,
        'expires_at': str,
        'exposure': int,
        'kind': str,
        'owner_active': bool,
        'privilege': int,
        'score': float,
        'sensitivity': int,
        'subject': str,
    },
    total=False,
)

CredentialRiskList = TypedDict(
    'CredentialRiskList',
    {
        'credentials': list[dict[str, Any]],
    },
    total=False,
)

DeploymentTarget = TypedDict(
    'DeploymentTarget',
    {
        'config': dict[str, Any],
        'connector': str,
        'created_at': str,
        'id': str,
        'name': str,
        'tenant_id': str,
    },
    total=False,
)

DeploymentTargetList = TypedDict(
    'DeploymentTargetList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

DeploymentTargetRequest = TypedDict(
    'DeploymentTargetRequest',
    {
        'config': dict[str, Any],
        'connector': str,
        'name': str,
    },
    total=False,
)

DiscoveryFinding = TypedDict(
    'DiscoveryFinding',
    {
        'discovered_at': str,
        'fingerprint': str,
        'id': str,
        'kind': str,
        'managed_identity_id': str,
        'metadata': dict[str, Any],
        'provenance': str,
        'ref': str,
        'risk_score': int,
        'run_id': str,
        'source_id': str,
        'tenant_id': str,
        'triage_actor': str,
        'triage_reason': str,
        'triage_status': str,
        'triaged_at': str,
    },
    total=False,
)

DiscoveryFindingList = TypedDict(
    'DiscoveryFindingList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

DiscoveryFindingTriageRequest = TypedDict(
    'DiscoveryFindingTriageRequest',
    {
        'managed_identity_id': str,
        'reason': str,
    },
    total=False,
)

DiscoveryMonitoring = TypedDict(
    'DiscoveryMonitoring',
    {
        'findings_path': str,
        'repository_path': str,
        'runs_path': str,
        'schedules_path': str,
        'sources': list[dict[str, Any]],
        'sources_path': str,
        'summary': dict[str, Any],
    },
    total=False,
)

DiscoveryMonitoringSource = TypedDict(
    'DiscoveryMonitoringSource',
    {
        'certificate_inventory_count': int,
        'completed_run_count': int,
        'failed_run_count': int,
        'finding_count': int,
        'findings_path': str,
        'kind': str,
        'last_discovery_at': str,
        'last_run_completed_at': str,
        'last_run_error': str,
        'last_run_id': str,
        'last_run_status': str,
        'monitoring_interval_seconds': int,
        'name': str,
        'open_finding_count': int,
        'repository_path': str,
        'run_count': int,
        'schedule_id': str,
        'scheduled': bool,
        'source_id': str,
        'updated_at': str,
    },
    total=False,
)

DiscoveryMonitoringSummary = TypedDict(
    'DiscoveryMonitoringSummary',
    {
        'active_monitoring_count': int,
        'certificate_inventory_count': int,
        'completed_run_count': int,
        'failed_run_count': int,
        'finding_count': int,
        'open_finding_count': int,
        'run_count': int,
        'scheduled_source_count': int,
        'source_count': int,
    },
    total=False,
)

DiscoveryRun = TypedDict(
    'DiscoveryRun',
    {
        'completed_at': str,
        'created_at': str,
        'discovered': int,
        'dry_run': bool,
        'error': str,
        'failed': int,
        'id': str,
        'rejected': int,
        'requested_by': str,
        'schedule_id': str,
        'source_id': str,
        'started_at': str,
        'status': str,
        'targets': int,
        'tenant_id': str,
    },
    total=False,
)

DiscoveryRunList = TypedDict(
    'DiscoveryRunList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

DiscoveryRunRequest = TypedDict(
    'DiscoveryRunRequest',
    {
        'dry_run': bool,
        'schedule_id': str,
        'source_id': str,
    },
    total=False,
)

DiscoverySchedule = TypedDict(
    'DiscoverySchedule',
    {
        'created_at': str,
        'enabled': bool,
        'id': str,
        'interval_seconds': int,
        'name': str,
        'source_id': str,
        'tenant_id': str,
        'updated_at': str,
    },
    total=False,
)

DiscoveryScheduleList = TypedDict(
    'DiscoveryScheduleList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

DiscoveryScheduleRequest = TypedDict(
    'DiscoveryScheduleRequest',
    {
        'enabled': bool,
        'interval_seconds': int,
        'name': str,
        'source_id': str,
    },
    total=False,
)

DiscoverySource = TypedDict(
    'DiscoverySource',
    {
        'config': dict[str, Any],
        'created_at': str,
        'id': str,
        'kind': str,
        'name': str,
        'tenant_id': str,
        'updated_at': str,
    },
    total=False,
)

DiscoverySourceList = TypedDict(
    'DiscoverySourceList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

DiscoverySourceRequest = TypedDict(
    'DiscoverySourceRequest',
    {
        'config': dict[str, Any],
        'kind': str,
        'name': str,
    },
    total=False,
)

DynamicLease = TypedDict(
    'DynamicLease',
    {
        'credential': str,
        'expires_at': str,
        'id': str,
        'issued_at': str,
        'provider': str,
        'role': str,
        'state': str,
    },
    total=False,
)

DynamicLeaseRenewRequest = TypedDict(
    'DynamicLeaseRenewRequest',
    {
        'extend_seconds': int,
    },
    total=False,
)

DynamicLeaseRequest = TypedDict(
    'DynamicLeaseRequest',
    {
        'provider': str,
        'role': str,
        'ttl_seconds': int,
    },
    total=False,
)

EditionFeature = TypedDict(
    'EditionFeature',
    {
        'licensed': bool,
        'mode': str,
        'name': str,
        'tier': str,
    },
    total=False,
)

EditionsInfo = TypedDict(
    'EditionsInfo',
    {
        'customer': str,
        'expires_at': str,
        'features': list[dict[str, Any]],
        'fips': dict[str, Any],
        'license_id': str,
        'read_only_at': str,
        'state': str,
        'tenant_band': int,
        'tier': str,
    },
    total=False,
)

EndpointBinding = TypedDict(
    'EndpointBinding',
    {
        'identity': dict[str, Any],
        'queued_lifecycle_intents': list[str],
        'renewal_intent': str,
        'target': dict[str, Any],
    },
    total=False,
)

EndpointBindingRequest = TypedDict(
    'EndpointBindingRequest',
    {
        'identity_name': str,
        'owner_id': str,
        'reason': str,
        'target': dict[str, Any],
        'target_id': str,
    },
    total=False,
)

EnrollmentToken = TypedDict(
    'EnrollmentToken',
    {
        'enroll_path': str,
        'token': str,
    },
    total=False,
)

EnterpriseProfessionalService = TypedDict(
    'EnterpriseProfessionalService',
    {
        'deliverables': list[str],
        'engagement_model': str,
        'id': str,
        'name': str,
    },
    total=False,
)

EnterpriseSupportSLATarget = TypedDict(
    'EnterpriseSupportSLATarget',
    {
        'applies_to': str,
        'escalation': str,
        'initial_response_sla': str,
        'severity': str,
        'target_restore': str,
        'update_cadence_sla': str,
    },
    total=False,
)

EnterpriseSupportStatus = TypedDict(
    'EnterpriseSupportStatus',
    {
        'capability': str,
        'contract_boundary': str,
        'evidence_refs': list[str],
        'license_feature': str,
        'license_state': str,
        'professional_services': list[dict[str, Any]],
        'served': bool,
        'sla_targets': list[dict[str, Any]],
        'support_mode': str,
        'support_tiers': list[dict[str, Any]],
        'tier': str,
    },
    total=False,
)

EnterpriseSupportTier = TypedDict(
    'EnterpriseSupportTier',
    {
        'contract_boundary': str,
        'coverage': str,
        'escalation': str,
        'id': str,
        'initial_response_sla': str,
        'license_mode': str,
        'name': str,
        'update_cadence_sla': str,
    },
    total=False,
)

EphemeralAPIKey = TypedDict(
    'EphemeralAPIKey',
    {
        'created_at': str,
        'expires_at': str,
        'id': str,
        'scopes': list[str],
        'subject': str,
        'tenant_id': str,
        'token': str,
    },
    total=False,
)

EphemeralAPIKeyRequest = TypedDict(
    'EphemeralAPIKeyRequest',
    {
        'scopes': list[str],
        'subject': str,
        'ttl_seconds': int,
    },
    total=False,
)

EphemeralApproval = TypedDict(
    'EphemeralApproval',
    {
        'action': str,
        'approvals': int,
        'approver': str,
        'resource': str,
    },
    total=False,
)

EphemeralApprovalRequest = TypedDict(
    'EphemeralApprovalRequest',
    {
        'action': str,
    },
    total=False,
)

EphemeralCredential = TypedDict(
    'EphemeralCredential',
    {
        'approvals': int,
        'attestation': dict[str, Any],
        'certificate_id': str,
        'certificate_pem': str,
        'credential_id': str,
        'expires_at': str,
        'not_after': str,
        'request_id': str,
        'required_approvals': int,
        'state': str,
        'subject': str,
    },
    total=False,
)

EphemeralCredentialRequest = TypedDict(
    'EphemeralCredentialRequest',
    {
        'method': str,
        'payload_base64': str,
        'public_key_pem': str,
        'request_id': str,
        'ttl_seconds': int,
    },
    total=False,
)

ExternalCA = TypedDict(
    'ExternalCA',
    {
        'id': str,
        'name': str,
        'status': str,
        'type': str,
    },
    total=False,
)

ExternalCAIssueRequest = TypedDict(
    'ExternalCAIssueRequest',
    {
        'csr_pem': str,
        'dns_names': list[str],
        'profile_name': str,
        'requested_ekus': list[str],
        'ttl_seconds': int,
    },
    total=False,
)

ExternalCAIssuedCertificate = TypedDict(
    'ExternalCAIssuedCertificate',
    {
        'certificate_pem': str,
        'issuer': str,
        'not_after': str,
        'serial': str,
    },
    total=False,
)

ExternalCAList = TypedDict(
    'ExternalCAList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

FIPSStatus = TypedDict(
    'FIPSStatus',
    {
        'build_target': str,
        'capability_id': str,
        'ci_gate': str,
        'crypto_boundary': str,
        'module': str,
        'module_active': bool,
        'product_certification_residual': str,
        'required': bool,
        'runtime_activation': list[str],
        'self_test_passed': bool,
        'standard': str,
        'validated_module_path': bool,
    },
    total=False,
)

FleetReissuanceActionRequest = TypedDict(
    'FleetReissuanceActionRequest',
    {
        'reason': str,
        'rollback_ref': str,
    },
    total=False,
)

FleetReissuanceBatch = TypedDict(
    'FleetReissuanceBatch',
    {
        'health_gate': str,
        'identity_ids': list[str],
        'index': int,
        'replacement_identity_ids': list[str],
        'status': str,
    },
    total=False,
)

FleetReissuanceEvidence = TypedDict(
    'FleetReissuanceEvidence',
    {
        'evidence_bundle': str,
        'evidence_bundle_format': str,
        'exported_at': str,
        'failed_targets': list[str],
        'rollback_refs': list[str],
        'run_id': str,
    },
    total=False,
)

FleetReissuanceHealthGate = TypedDict(
    'FleetReissuanceHealthGate',
    {
        'name': str,
        'status': str,
    },
    total=False,
)

FleetReissuanceRequest = TypedDict(
    'FleetReissuanceRequest',
    {
        'batch_size': int,
        'connector': str,
        'evidence_hint': str,
        'health_gates': list[dict[str, Any]],
        'issuer_id': str,
        'reason': str,
        'rollback_ref': str,
        'target': str,
    },
    total=False,
)

FleetReissuanceRun = TypedDict(
    'FleetReissuanceRun',
    {
        'affected_identity_ids': list[str],
        'batch_count': int,
        'batch_size': int,
        'batches': list[dict[str, Any]],
        'connector': str,
        'connector_deliveries': list[dict[str, Any]],
        'connector_delivery_ids': list[str],
        'created_at': str,
        'created_by': str,
        'evidence_bundle': str,
        'evidence_bundle_format': str,
        'failed_targets': list[str],
        'graph_impact': dict[str, Any],
        'health_gates': list[dict[str, Any]],
        'id': str,
        'idempotency_key': str,
        'issuer_id': str,
        'phase': str,
        'reason': str,
        'replacement_identities': list[dict[str, Any]],
        'replacement_identity_ids': list[str],
        'revoked_identity_ids': list[str],
        'rollback_refs': list[str],
        'status': str,
        'target': str,
        'tenant_id': str,
        'updated_at': str,
    },
    total=False,
)

FleetReissuanceRunList = TypedDict(
    'FleetReissuanceRunList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

GraphEdge = TypedDict(
    'GraphEdge',
    {
        'from': str,
        'to': str,
        'type': str,
    },
    total=False,
)

GraphImpact = TypedDict(
    'GraphImpact',
    {
        'affected': list[dict[str, Any]],
        'by_kind': dict[str, Any],
        'node': dict[str, Any],
    },
    total=False,
)

GraphNode = TypedDict(
    'GraphNode',
    {
        'attrs': dict[str, Any],
        'id': str,
        'kind': str,
        'name': str,
    },
    total=False,
)

GraphQueryResult = TypedDict(
    'GraphQueryResult',
    {
        'rows': list[dict[str, Any]],
    },
    total=False,
)

GraphReachable = TypedDict(
    'GraphReachable',
    {
        'from': str,
        'nodes': list[dict[str, Any]],
    },
    total=False,
)

GraphResponse = TypedDict(
    'GraphResponse',
    {
        'edges': list[dict[str, Any]],
        'nodes': list[dict[str, Any]],
    },
    total=False,
)

ITSMTicket = TypedDict(
    'ITSMTicket',
    {
        'created_at': str,
        'destination': str,
        'id': str,
        'idempotency_key': str,
        'outbox_id': int,
        'provider': str,
        'status': str,
        'table': str,
        'tenant_id': str,
    },
    total=False,
)

Identity = TypedDict(
    'Identity',
    {
        'attributes': dict[str, Any],
        'created_at': str,
        'id': str,
        'issuer_id': str,
        'kind': str,
        'name': str,
        'not_after': str,
        'not_before': str,
        'owner_id': str,
        'status': str,
        'tenant_id': str,
    },
    total=False,
)

IdentityConnectorTargetRequest = TypedDict(
    'IdentityConnectorTargetRequest',
    {
        'target_id': str,
    },
    total=False,
)

IdentityList = TypedDict(
    'IdentityList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

IdentityRequest = TypedDict(
    'IdentityRequest',
    {
        'attributes': dict[str, Any],
        'issuer_id': str,
        'kind': str,
        'name': str,
        'owner_id': str,
    },
    total=False,
)

IncidentExecution = TypedDict(
    'IncidentExecution',
    {
        'blast_radius': dict[str, Any],
        'compromised_identity_id': str,
        'connector_delivery': dict[str, Any],
        'connector_delivery_id': str,
        'created_at': str,
        'created_by': str,
        'evidence_bundle': str,
        'evidence_bundle_format': str,
        'failed_targets': list[str],
        'id': str,
        'idempotency_key': str,
        'phase': str,
        'reason': str,
        'replacement_identity': dict[str, Any],
        'replacement_identity_id': str,
        'revocation_status': str,
        'rollback_refs': list[str],
        'status': str,
        'tenant_id': str,
        'updated_at': str,
    },
    total=False,
)

IncidentExecutionList = TypedDict(
    'IncidentExecutionList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

IncidentExecutionRequest = TypedDict(
    'IncidentExecutionRequest',
    {
        'connector': str,
        'delivery_rollback_ref': str,
        'identity_id': str,
        'reason': str,
        'replacement_name': str,
        'target': str,
    },
    total=False,
)

Issuer = TypedDict(
    'Issuer',
    {
        'chain': list[str],
        'chainless': bool,
        'created_at': str,
        'id': str,
        'internal': bool,
        'kind': str,
        'name': str,
        'public_key': str,
        'tenant_id': str,
    },
    total=False,
)

IssuerList = TypedDict(
    'IssuerList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

IssuerRequest = TypedDict(
    'IssuerRequest',
    {
        'chain': list[str],
        'internal': bool,
        'kind': str,
        'name': str,
        'public_key': str,
    },
    total=False,
)

MCPToolCall = TypedDict(
    'MCPToolCall',
    {
        'authority_id': str,
        'csr_pem': str,
        'previous_serial': str,
        'reason': str,
        'subject': str,
        'ttl_seconds': int,
    },
    total=False,
)

MCPToolList = TypedDict(
    'MCPToolList',
    {
        'identity': str,
        'read_only': bool,
        'tools': list[str],
    },
    total=False,
)

MCPToolResult = TypedDict(
    'MCPToolResult',
    {
        'certificate_pem': str,
        'citations': list[str],
        'not_after': str,
        'serial': str,
        'text': str,
        'tool': str,
    },
    total=False,
)

MachineLoginRequest = TypedDict(
    'MachineLoginRequest',
    {
        'credential': str,
        'method': str,
    },
    total=False,
)

MachineLoginResponse = TypedDict(
    'MachineLoginResponse',
    {
        'expires_at': str,
        'method': str,
        'principal': str,
        'scopes': list[str],
        'session_id': str,
    },
    total=False,
)

ManagedKey = TypedDict(
    'ManagedKey',
    {
        'algorithm': str,
        'extractable': bool,
        'key_id': str,
        'public_der': str,
        'state': str,
        'version': int,
    },
    total=False,
)

ManagedKeyActionRequest = TypedDict(
    'ManagedKeyActionRequest',
    {
        'key_id': str,
    },
    total=False,
)

ManagedKeyGenerateRequest = TypedDict(
    'ManagedKeyGenerateRequest',
    {
        'algorithm': str,
    },
    total=False,
)

ManagedOfferingStatus = TypedDict(
    'ManagedOfferingStatus',
    {
        'deployment_model': str,
        'event_type': str,
        'idempotency_required': bool,
        'license_state': str,
        'mutation_path': str,
        'provider_plane_mode': str,
        'served': bool,
        'tenant_band': int,
        'tier': str,
    },
    total=False,
)

ManagedTenant = TypedDict(
    'ManagedTenant',
    {
        'created_at': str,
        'data_residency': str,
        'deployment_model': str,
        'event_sequence': int,
        'managed': bool,
        'name': str,
        'plan': str,
        'provider_tenant_id': str,
        'provisioned_by': str,
        'region': str,
        'slo_tier': str,
        'support_tier': str,
        'tenant_id': str,
    },
    total=False,
)

ManagedTenantProvisionRequest = TypedDict(
    'ManagedTenantProvisionRequest',
    {
        'data_residency': str,
        'name': str,
        'plan': str,
        'region': str,
        'slo_tier': str,
        'support_tier': str,
        'tenant_id': str,
    },
    total=False,
)

Member = TypedDict(
    'Member',
    {
        'created_at': str,
        'display_name': str,
        'email': str,
        'offboard_reason': str,
        'offboarded_at': str,
        'offboarded_by': str,
        'roles': list[str],
        'source': str,
        'status': str,
        'subject': str,
        'tenant_id': str,
        'updated_at': str,
    },
    total=False,
)

MemberList = TypedDict(
    'MemberList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

MemberRequest = TypedDict(
    'MemberRequest',
    {
        'display_name': str,
        'email': str,
        'roles': list[str],
        'source': str,
    },
    total=False,
)

NHIDecommissionItem = TypedDict(
    'NHIDecommissionItem',
    {
        'action': str,
        'error': str,
        'evidence_refs': list[str],
        'from': str,
        'identity_id': str,
        'kind': str,
        'name': str,
        'owner_id': str,
        'signal_type': str,
        'to': str,
    },
    total=False,
)

NHIDecommissionRequest = TypedDict(
    'NHIDecommissionRequest',
    {
        'reason': str,
        'revocation_reason': str,
        'signals': list[dict[str, Any]],
    },
    total=False,
)

NHIDecommissionResponse = TypedDict(
    'NHIDecommissionResponse',
    {
        'capability': str,
        'coverage': list[str],
        'items': list[dict[str, Any]],
        'reason': str,
        'summary': dict[str, Any],
    },
    total=False,
)

NHIDecommissionSignal = TypedDict(
    'NHIDecommissionSignal',
    {
        'evidence_refs': list[str],
        'identity_id': str,
        'inactive_before': str,
        'owner_id': str,
        'owner_name': str,
        'subject': str,
        'type': str,
        'vendor_name': str,
    },
    total=False,
)

NHIDecommissionSummary = TypedDict(
    'NHIDecommissionSummary',
    {
        'failed': int,
        'retired': int,
        'revoked': int,
        'skipped': int,
        'total_matched': int,
    },
    total=False,
)

NHIInventory = TypedDict(
    'NHIInventory',
    {
        'coverage': list[str],
        'generated_at': str,
        'items': list[dict[str, Any]],
        'summary': dict[str, Any],
    },
    total=False,
)

NHIInventoryItem = TypedDict(
    'NHIInventoryItem',
    {
        'created_at': str,
        'discovered_at': str,
        'display_name': str,
        'fingerprint': str,
        'id': str,
        'kind': str,
        'metadata': dict[str, Any],
        'not_after': str,
        'not_before': str,
        'owner_id': str,
        'provenance': str,
        'ref': str,
        'risk_score': int,
        'source': str,
        'status': str,
        'tenant_id': str,
    },
    total=False,
)

NHIOverPrivilegeFinding = TypedDict(
    'NHIOverPrivilegeFinding',
    {
        'display_name': str,
        'evidence_refs': list[str],
        'finding_types': list[str],
        'granted_scopes': list[str],
        'inventory_id': str,
        'kind': str,
        'last_used_at': str,
        'owner_id': str,
        'recommendation': str,
        'recommended_scopes': list[str],
        'ref': str,
        'risk_score': int,
        'severity': str,
        'source': str,
        'status': str,
        'unused_ratio': float,
        'unused_scopes': list[str],
        'used_scopes': list[str],
    },
    total=False,
)

NHIOverPrivilegePosture = TypedDict(
    'NHIOverPrivilegePosture',
    {
        'capability': str,
        'coverage': list[str],
        'findings': list[dict[str, Any]],
        'generated_at': str,
        'summary': dict[str, Any],
    },
    total=False,
)

NHIOverPrivilegeSummary = TypedDict(
    'NHIOverPrivilegeSummary',
    {
        'critical': int,
        'high': int,
        'least_privilege_plans': int,
        'low': int,
        'medium': int,
        'overprivileged': int,
        'total_analyzed': int,
        'unused_grants': int,
        'wildcard_grants': int,
    },
    total=False,
)

NHIReviewCampaign = TypedDict(
    'NHIReviewCampaign',
    {
        'certified_count': int,
        'completed_at': str,
        'created_at': str,
        'due_at': str,
        'exception_count': int,
        'id': str,
        'item_count': int,
        'items': list[dict[str, Any]],
        'name': str,
        'pending_count': int,
        'requested_by': str,
        'reviewer_subject': str,
        'revoked_count': int,
        'scope': str,
        'status': str,
        'tenant_id': str,
        'updated_at': str,
    },
    total=False,
)

NHIReviewCampaignList = TypedDict(
    'NHIReviewCampaignList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

NHIReviewCampaignStartRequest = TypedDict(
    'NHIReviewCampaignStartRequest',
    {
        'due_at': str,
        'id': str,
        'items': list[dict[str, Any]],
        'name': str,
        'reviewer_subject': str,
        'scope': str,
    },
    total=False,
)

NHIReviewDecisionRequest = TypedDict(
    'NHIReviewDecisionRequest',
    {
        'decision': str,
        'decision_evidence_refs': list[str],
        'reason': str,
        'reviewer_subject': str,
    },
    total=False,
)

NHIReviewItem = TypedDict(
    'NHIReviewItem',
    {
        'created_at': str,
        'decided_at': str,
        'decision_by': str,
        'decision_evidence_refs': list[str],
        'decision_reason': str,
        'display_name': str,
        'entitlement': str,
        'evidence_refs': list[str],
        'item_id': str,
        'nhi_id': str,
        'nhi_kind': str,
        'owner_ref': str,
        'resource': str,
        'risk': str,
        'status': str,
        'updated_at': str,
    },
    total=False,
)

NHIReviewItemRequest = TypedDict(
    'NHIReviewItemRequest',
    {
        'display_name': str,
        'entitlement': str,
        'evidence_refs': list[str],
        'item_id': str,
        'nhi_id': str,
        'nhi_kind': str,
        'owner_ref': str,
        'resource': str,
        'risk': str,
    },
    total=False,
)

NHIStaleFinding = TypedDict(
    'NHIStaleFinding',
    {
        'activity_age_days': int,
        'created_age_days': int,
        'created_at': str,
        'display_name': str,
        'evidence_refs': list[str],
        'finding_types': list[str],
        'inventory_id': str,
        'kind': str,
        'last_activity_at': str,
        'last_seen_at': str,
        'last_used_at': str,
        'owner_id': str,
        'owner_status': str,
        'recommendation': str,
        'ref': str,
        'risk_score': int,
        'severity': str,
        'source': str,
        'status': str,
    },
    total=False,
)

NHIStalePosture = TypedDict(
    'NHIStalePosture',
    {
        'capability': str,
        'coverage': list[str],
        'findings': list[dict[str, Any]],
        'generated_at': str,
        'summary': dict[str, Any],
        'thresholds': dict[str, Any],
    },
    total=False,
)

NHIStaleSummary = TypedDict(
    'NHIStaleSummary',
    {
        'critical': int,
        'dormant': int,
        'findings': int,
        'high': int,
        'low': int,
        'medium': int,
        'orphaned': int,
        'recommendations': int,
        'stale': int,
        'total_analyzed': int,
        'unused': int,
    },
    total=False,
)

NHIStaleThresholds = TypedDict(
    'NHIStaleThresholds',
    {
        'dormant_activity_days': int,
        'stale_activity_days': int,
        'unused_no_activity_days': int,
    },
    total=False,
)

NHIStaticFinding = TypedDict(
    'NHIStaticFinding',
    {
        'created_at': str,
        'credential_age_days': int,
        'display_name': str,
        'evidence_refs': list[str],
        'expires_at': str,
        'finding_types': list[str],
        'inventory_id': str,
        'kind': str,
        'last_rotated_at': str,
        'owner_id': str,
        'owner_status': str,
        'recommendation': str,
        'ref': str,
        'risk_score': int,
        'rotation_age_days': int,
        'severity': str,
        'source': str,
        'status': str,
        'ttl_days': int,
    },
    total=False,
)

NHIStaticPosture = TypedDict(
    'NHIStaticPosture',
    {
        'capability': str,
        'coverage': list[str],
        'findings': list[dict[str, Any]],
        'generated_at': str,
        'summary': dict[str, Any],
        'thresholds': dict[str, Any],
    },
    total=False,
)

NHIStaticSummary = TypedDict(
    'NHIStaticSummary',
    {
        'critical': int,
        'findings': int,
        'high': int,
        'long_lived': int,
        'low': int,
        'medium': int,
        'no_expiry': int,
        'recommendations': int,
        'rotation_overdue': int,
        'static_credentials': int,
        'total_analyzed': int,
    },
    total=False,
)

NHIStaticThresholds = TypedDict(
    'NHIStaticThresholds',
    {
        'long_lived_credential_days': int,
        'no_expiry_minimum_age_days': int,
        'rotation_overdue_days': int,
    },
    total=False,
)

Notification = TypedDict(
    'Notification',
    {
        'attempts': int,
        'certificate_id': str,
        'created_at': str,
        'delivered_at': str,
        'destination': str,
        'detail': str,
        'escalation_recipients': list[dict[str, Any]],
        'id': str,
        'idempotency_key': str,
        'kind': str,
        'last_error': str,
        'not_after': str,
        'owner_email': str,
        'owner_id': str,
        'owner_name': str,
        'read_at': str,
        'routing_policy_id': str,
        'serial': str,
        'severity': str,
        'status': str,
        'subject': str,
        'tenant_id': str,
        'threshold_days': int,
    },
    total=False,
)

NotificationChannel = TypedDict(
    'NotificationChannel',
    {
        'category': str,
        'configured': bool,
        'delivery': str,
        'description': str,
        'id': str,
        'label': str,
    },
    total=False,
)

NotificationChannelList = TypedDict(
    'NotificationChannelList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

NotificationList = TypedDict(
    'NotificationList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

OIDCMappingStatus = TypedDict(
    'OIDCMappingStatus',
    {
        'allow_default_tenant': bool,
        'claim_is_tenant': bool,
        'default_roles': list[str],
        'default_tenant': str,
        'enabled': bool,
        'groups_claim': str,
        'tenant_claim': str,
        'tenant_mappings': list[dict[str, Any]],
    },
    total=False,
)

OIDCTenantMapping = TypedDict(
    'OIDCTenantMapping',
    {
        'claim': str,
        'group': str,
        'roles': list[str],
        'subject': str,
        'tenant_id': str,
    },
    total=False,
)

OffboardMemberRequest = TypedDict(
    'OffboardMemberRequest',
    {
        'reason': str,
    },
    total=False,
)

OffboardMemberResponse = TypedDict(
    'OffboardMemberResponse',
    {
        'member': dict[str, Any],
        'revoked_token_count': int,
        'rotation_evidence': str,
    },
    total=False,
)

OutboxCircuit = TypedDict(
    'OutboxCircuit',
    {
        'destination': str,
        'failures': int,
        'last_error': str,
        'open_until': str,
        'state': str,
        'tenant_id': str,
        'updated_at': str,
    },
    total=False,
)

OutboxCircuitList = TypedDict(
    'OutboxCircuitList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

Owner = TypedDict(
    'Owner',
    {
        'created_at': str,
        'email': str,
        'id': str,
        'kind': str,
        'name': str,
        'tenant_id': str,
    },
    total=False,
)

OwnerList = TypedDict(
    'OwnerList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

OwnerRequest = TypedDict(
    'OwnerRequest',
    {
        'email': str,
        'kind': str,
        'name': str,
    },
    total=False,
)

OwnershipAttribution = TypedDict(
    'OwnershipAttribution',
    {
        'coverage': list[str],
        'generated_at': str,
        'items': list[dict[str, Any]],
        'summary': dict[str, Any],
    },
    total=False,
)

OwnershipAttributionItem = TypedDict(
    'OwnershipAttributionItem',
    {
        'attribution_evidence': list[str],
        'attribution_source': str,
        'attribution_status': str,
        'created_at': str,
        'discovered_at': str,
        'display_name': str,
        'id': str,
        'kind': str,
        'owner': dict[str, Any],
        'ref': str,
        'source': str,
        'tenant_id': str,
    },
    total=False,
)

OwnershipAttributionOwner = TypedDict(
    'OwnershipAttributionOwner',
    {
        'email': str,
        'id': str,
        'kind': str,
        'name': str,
        'tenant_id': str,
    },
    total=False,
)

PAMPostgresCredential = TypedDict(
    'PAMPostgresCredential',
    {
        'dsn': str,
        'username': str,
    },
    total=False,
)

PAMSSHCredential = TypedDict(
    'PAMSSHCredential',
    {
        'certificate': str,
        'key_id': str,
        'principal': str,
        'serial': int,
        'valid_before': str,
    },
    total=False,
)

PAMSession = TypedDict(
    'PAMSession',
    {
        'attestation': dict[str, Any],
        'audit': dict[str, Any],
        'ended_at': str,
        'expires_at': str,
        'id': str,
        'postgres': dict[str, Any],
        'reason': str,
        'requested_by': str,
        'role': str,
        'ssh': dict[str, Any],
        'started_at': str,
        'status': str,
        'subject': str,
        'target_id': str,
        'target_type': str,
    },
    total=False,
)

PAMSessionList = TypedDict(
    'PAMSessionList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

PAMSessionRequest = TypedDict(
    'PAMSessionRequest',
    {
        'method': str,
        'payload_base64': str,
        'reason': str,
        'role': str,
        'ssh_principal': str,
        'ssh_public_key': str,
        'target_id': str,
        'target_type': str,
        'ttl_seconds': int,
    },
    total=False,
)

PKISecret = TypedDict(
    'PKISecret',
    {
        'certificate': str,
        'common_name': str,
        'private_key': str,
        'serial': str,
    },
    total=False,
)

PKISecretRequest = TypedDict(
    'PKISecretRequest',
    {
        'common_name': str,
        'ttl_seconds': int,
    },
    total=False,
)

PQCMigration = TypedDict(
    'PQCMigration',
    {
        'effective_algorithm': str,
        'migration_progress': dict[str, Any],
        'protocol': str,
        'queued': int,
        'queued_at': str,
        'rollback_configured': bool,
        'run_id': str,
        'target_algorithm': str,
    },
    total=False,
)

PQCMigrationRequest = TypedDict(
    'PQCMigrationRequest',
    {
        'asset_ids': list[str],
        'protocol': str,
        'rollback_on_failure': bool,
        'target_algorithm': str,
    },
    total=False,
)

PQCMigrationRollback = TypedDict(
    'PQCMigrationRollback',
    {
        'migration_progress': dict[str, Any],
        'queued': int,
        'queued_at': str,
        'reason': str,
        'run_id': str,
    },
    total=False,
)

PQCMigrationRollbackRequest = TypedDict(
    'PQCMigrationRollbackRequest',
    {
        'asset_ids': list[str],
        'reason': str,
    },
    total=False,
)

PrivacyCatalog = TypedDict(
    'PrivacyCatalog',
    {
        'items': list[dict[str, Any]],
    },
    total=False,
)

PrivacyCatalogEntry = TypedDict(
    'PrivacyCatalogEntry',
    {
        'category': str,
        'erasure': str,
        'id': str,
        'location': str,
        'owner': str,
        'purpose': str,
        'retention_class': str,
    },
    total=False,
)

PrivacyErasureSelectors = TypedDict(
    'PrivacyErasureSelectors',
    {
        'attestation_ids': list[str],
        'certificate_fingerprints': list[str],
        'identity_ids': list[str],
        'owner_ids': list[str],
        'ssh_key_ids': list[str],
    },
    total=False,
)

PrivacyRetentionCutoffs = TypedDict(
    'PrivacyRetentionCutoffs',
    {
        'access_terminal_before': str,
        'agent_stale_before': str,
        'approval_actor_before': str,
        'attestation_evidence_before': str,
        'certificate_terminal_before': str,
        'identity_terminal_before': str,
        'owner_inactive_before': str,
        'profile_actor_before': str,
        'ssh_stale_before': str,
    },
    total=False,
)

PrivacyRetentionRun = TypedDict(
    'PrivacyRetentionRun',
    {
        'counts': dict[str, Any],
        'cutoffs': dict[str, Any],
        'enforced_at': str,
        'requested_by_ref': str,
        'run_id': str,
    },
    total=False,
)

PrivacyRetentionRunList = TypedDict(
    'PrivacyRetentionRunList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

PrivacySubjectErasure = TypedDict(
    'PrivacySubjectErasure',
    {
        'counts': dict[str, Any],
        'erased_at': str,
        'reason': str,
        'requested_by_ref': str,
        'selectors': dict[str, Any],
        'subject_ref': str,
    },
    total=False,
)

PrivacySubjectErasureList = TypedDict(
    'PrivacySubjectErasureList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

PrivacySubjectErasureRequest = TypedDict(
    'PrivacySubjectErasureRequest',
    {
        'reason': str,
        'subject': str,
    },
    total=False,
)

PrivacySubjectExport = TypedDict(
    'PrivacySubjectExport',
    {
        'api_tokens': list[dict[str, Any]],
        'approvals': list[dict[str, Any]],
        'attestations': list[dict[str, Any]],
        'certificates': list[dict[str, Any]],
        'counts': dict[str, Any],
        'generated_at': str,
        'identities': list[dict[str, Any]],
        'owners': list[dict[str, Any]],
        'ssh_keys': list[dict[str, Any]],
        'subject': str,
        'subject_ref': str,
        'tenant_id': str,
        'tenant_members': list[dict[str, Any]],
    },
    total=False,
)

PrivacySubjectExportRequest = TypedDict(
    'PrivacySubjectExportRequest',
    {
        'subject': str,
    },
    total=False,
)

Problem = TypedDict(
    'Problem',
    {
        'detail': str,
        'instance': str,
        'status': int,
        'title': str,
        'type': str,
    },
    total=False,
)

Profile = TypedDict(
    'Profile',
    {
        'active': bool,
        'created_by': str,
        'id': str,
        'name': str,
        'spec': dict[str, Any],
        'version': int,
    },
    total=False,
)

ProfileList = TypedDict(
    'ProfileList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

ProfileRequest = TypedDict(
    'ProfileRequest',
    {
        'name': str,
        'spec': dict[str, Any],
    },
    total=False,
)

RCARequest = TypedDict(
    'RCARequest',
    {
        'question': str,
        'subject': str,
    },
    total=False,
)

RemediationPlaybook = TypedDict(
    'RemediationPlaybook',
    {
        'action': str,
        'capability': str,
        'evidence_sources': list[str],
        'external_effect': str,
        'id': str,
        'name': str,
        'required_inputs': list[str],
        'status': str,
        'summary': str,
    },
    total=False,
)

RemediationPlaybookCatalog = TypedDict(
    'RemediationPlaybookCatalog',
    {
        'capability': str,
        'generated_at': str,
        'items': list[dict[str, Any]],
        'status': str,
    },
    total=False,
)

RemediationPlaybookRun = TypedDict(
    'RemediationPlaybookRun',
    {
        'action': str,
        'connector': str,
        'connector_delivery': dict[str, Any],
        'connector_delivery_id': str,
        'created_at': str,
        'created_by': str,
        'evidence_refs': list[str],
        'id': str,
        'idempotency_key': str,
        'inventory_id': str,
        'outbox_id': int,
        'phase': str,
        'playbook_id': str,
        'reason': str,
        'rollback_refs': list[str],
        'scope_delta': dict[str, Any],
        'status': str,
        'target': str,
        'target_identity_id': str,
        'tenant_id': str,
        'updated_at': str,
    },
    total=False,
)

RemediationPlaybookRunList = TypedDict(
    'RemediationPlaybookRunList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

RemediationPlaybookRunRequest = TypedDict(
    'RemediationPlaybookRunRequest',
    {
        'connector': str,
        'inventory_id': str,
        'reason': str,
        'recommended_scopes': list[str],
        'remove_scopes': list[str],
        'replacement_name': str,
        'rollback_ref': str,
        'target': str,
        'target_identity_id': str,
    },
    total=False,
)

RiskComponents = TypedDict(
    'RiskComponents',
    {
        'age': float,
        'exposure': float,
        'owner': float,
        'privilege': float,
        'rotation': float,
        'sensitivity': float,
    },
    total=False,
)

Role = TypedDict(
    'Role',
    {
        'name': str,
        'permissions': list[str],
    },
    total=False,
)

RoleList = TypedDict(
    'RoleList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

RotationRun = TypedDict(
    'RotationRun',
    {
        'completed_at': str,
        'created_at': str,
        'error': str,
        'id': str,
        'idempotency_key': str,
        'identity_id': str,
        'outbox_id': int,
        'predecessor_fingerprint': str,
        'reason': str,
        'rollback_ref': str,
        'status': str,
        'successor_fingerprint': str,
        'tenant_id': str,
        'trigger': str,
        'updated_at': str,
    },
    total=False,
)

RotationRunList = TypedDict(
    'RotationRunList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

SSHAttestedUserCert = TypedDict(
    'SSHAttestedUserCert',
    {
        'attestation': dict[str, Any],
        'certificate': str,
        'key_id': str,
        'principals': list[str],
        'serial': int,
        'subject': str,
        'valid_before': str,
    },
    total=False,
)

SSHAttestedUserCertRequest = TypedDict(
    'SSHAttestedUserCertRequest',
    {
        'key_id': str,
        'method': str,
        'payload_base64': str,
        'public_key': str,
        'ttl_seconds': int,
    },
    total=False,
)

SSHHostRetireRequest = TypedDict(
    'SSHHostRetireRequest',
    {
        'host': str,
        'identity_id': str,
        'reason': str,
        'run_id': str,
        'source_id': str,
    },
    total=False,
)

SSHHostRetirement = TypedDict(
    'SSHHostRetirement',
    {
        'host': str,
        'id': str,
        'identity_id': str,
        'reason': str,
        'recorded_at': str,
        'run_id': str,
        'source_id': str,
        'status': str,
        'tenant_id': str,
    },
    total=False,
)

SSHRevokeCertificateRequest = TypedDict(
    'SSHRevokeCertificateRequest',
    {
        'key_id': str,
        'reason': str,
        'serial': int,
    },
    total=False,
)

SSHStatus = TypedDict(
    'SSHStatus',
    {
        'attestors': list[str],
        'authority_key': str,
        'krl_version': int,
        'revoked_count': int,
        'served': bool,
        'tenant_id': str,
    },
    total=False,
)

SSHTrustRollout = TypedDict(
    'SSHTrustRollout',
    {
        'candidate_ca_fingerprint': str,
        'confirmed': bool,
        'health_command': str,
        'id': str,
        'recorded_at': str,
        'reload_command': str,
        'rollback_plan': str,
        'source_id': str,
        'status': str,
        'target_hosts': list[str],
        'tenant_id': str,
    },
    total=False,
)

SSHTrustRolloutRequest = TypedDict(
    'SSHTrustRolloutRequest',
    {
        'candidate_ca_fingerprint': str,
        'confirmed': bool,
        'health_command': str,
        'reload_command': str,
        'rollback_plan': str,
        'source_id': str,
        'status': str,
        'target_hosts': list[str],
    },
    total=False,
)

SecretImportRequest = TypedDict(
    'SecretImportRequest',
    {
        'prefix': str,
        'values': dict[str, Any],
    },
    total=False,
)

SecretMeta = TypedDict(
    'SecretMeta',
    {
        'created_at': str,
        'name': str,
        'updated_at': str,
        'version': int,
    },
    total=False,
)

SecretMetaList = TypedDict(
    'SecretMetaList',
    {
        'items': list[dict[str, Any]],
        'next_cursor': str,
    },
    total=False,
)

SecretRecoverRequest = TypedDict(
    'SecretRecoverRequest',
    {
        'at': str,
    },
    total=False,
)

SecretRequest = TypedDict(
    'SecretRequest',
    {
        'name': str,
        'value': str,
    },
    total=False,
)

SecretRotation = TypedDict(
    'SecretRotation',
    {
        'completed': bool,
        'error': str,
        'failed_phase': str,
        'key': str,
        'new_ref': str,
        'old_ref': str,
        'rollback_attempted': bool,
        'rollback_error': str,
        'rollback_failed': bool,
        'rolled_back': bool,
    },
    total=False,
)

SecretRotationRequest = TypedDict(
    'SecretRotationRequest',
    {
        'key': str,
        'old_ref': str,
        'provider': str,
    },
    total=False,
)

SecretScan = TypedDict(
    'SecretScan',
    {
        'engine_version': str,
        'findings': list[dict[str, Any]],
        'findings_count': int,
        'rules_active': int,
        'run_id': str,
        'scanner': str,
    },
    total=False,
)

SecretScanFinding = TypedDict(
    'SecretScanFinding',
    {
        'credential_ref': str,
        'file': str,
        'line': int,
        'rule_id': str,
    },
    total=False,
)

SecretScanRequest = TypedDict(
    'SecretScanRequest',
    {
        'path': str,
    },
    total=False,
)

SecretSync = TypedDict(
    'SecretSync',
    {
        'delivered': bool,
        'enqueued': bool,
        'name': str,
        'remote_key': str,
        'target': str,
    },
    total=False,
)

SecretSyncRequest = TypedDict(
    'SecretSyncRequest',
    {
        'name': str,
        'remote_key': str,
        'target': str,
    },
    total=False,
)

SecretValue = TypedDict(
    'SecretValue',
    {
        'name': str,
        'value': str,
        'version': int,
    },
    total=False,
)

ServiceNowTicketRequest = TypedDict(
    'ServiceNowTicketRequest',
    {
        'allow_private_endpoint': bool,
        'category': str,
        'correlation_id': str,
        'description': str,
        'impact': str,
        'instance_url': str,
        'short_description': str,
        'table': str,
        'token_ref': str,
        'urgency': str,
    },
    total=False,
)

ShareRedeemRequest = TypedDict(
    'ShareRedeemRequest',
    {
        'token': str,
    },
    total=False,
)

ShareRequest = TypedDict(
    'ShareRequest',
    {
        'ttl_seconds': int,
        'value': str,
    },
    total=False,
)

ShareToken = TypedDict(
    'ShareToken',
    {
        'expires_at': str,
        'token': str,
    },
    total=False,
)

ShareValue = TypedDict(
    'ShareValue',
    {
        'value': str,
    },
    total=False,
)

TransitCiphertext = TypedDict(
    'TransitCiphertext',
    {
        'ciphertext': str,
        'version': int,
    },
    total=False,
)

TransitDecryptRequest = TypedDict(
    'TransitDecryptRequest',
    {
        'aad': str,
        'ciphertext': str,
        'key': str,
    },
    total=False,
)

TransitEncryptRequest = TypedDict(
    'TransitEncryptRequest',
    {
        'aad': str,
        'key': str,
        'plaintext': str,
    },
    total=False,
)

TransitHMAC = TypedDict(
    'TransitHMAC',
    {
        'hmac': str,
    },
    total=False,
)

TransitHMACRequest = TypedDict(
    'TransitHMACRequest',
    {
        'data': str,
        'key': str,
    },
    total=False,
)

TransitKey = TypedDict(
    'TransitKey',
    {
        'kind': str,
        'name': str,
        'version': int,
    },
    total=False,
)

TransitKeyRequest = TypedDict(
    'TransitKeyRequest',
    {
        'kind': str,
        'name': str,
    },
    total=False,
)

TransitPlaintext = TypedDict(
    'TransitPlaintext',
    {
        'plaintext': str,
    },
    total=False,
)

TransitRewrapRequest = TypedDict(
    'TransitRewrapRequest',
    {
        'aad': str,
        'ciphertext': str,
        'key': str,
    },
    total=False,
)

TransitRotateRequest = TypedDict(
    'TransitRotateRequest',
    {
        'name': str,
    },
    total=False,
)

TransitSignRequest = TypedDict(
    'TransitSignRequest',
    {
        'key': str,
        'message': str,
    },
    total=False,
)

TransitSignature = TypedDict(
    'TransitSignature',
    {
        'public_der': str,
        'signature': str,
    },
    total=False,
)

TransitVerify = TypedDict(
    'TransitVerify',
    {
        'valid': bool,
    },
    total=False,
)

TransitVerifyRequest = TypedDict(
    'TransitVerifyRequest',
    {
        'message': str,
        'public_der': str,
        'signature': str,
    },
    total=False,
)

TransitionRequest = TypedDict(
    'TransitionRequest',
    {
        'reason': str,
        'to': str,
    },
    total=False,
)

Schema = dict[str, Any]
