// Package winservice describes how the trustctl agent registers and runs as a
// Windows service, and renders the WiX source for its MSI installer.
//
// The service specification (name, start type, executable, arguments) and the
// WiX/MSI rendering are platform-neutral and live here so they can be built and
// tested anywhere. The actual Service Control Manager calls — installing,
// removing, and running under the SCM — are Windows-only and live in
// scm_windows.go behind a build tag.
package winservice

import (
	"errors"
	"strings"
	"text/template"
)

// DefaultServiceName is the Windows service (and key) name.
const DefaultServiceName = "trustctl-agent"

// upgradeCode is the MSI UpgradeCode: a stable GUID that identifies the product
// family across versions so each MSI upgrades in place rather than installing
// side by side. It must never change for trustctl-agent.
const upgradeCode = "5F1B5E4C-9A2D-4C3E-8B7A-2E6D9C1F0A34"

// Config describes the service to register.
type Config struct {
	// Name is the service name; defaults to DefaultServiceName.
	Name string
	// DisplayName and Description are shown in the Services console; defaulted
	// when empty.
	DisplayName string
	Description string
	// ExePath is the absolute path to the agent executable (required).
	ExePath string
	// Arguments are passed to the executable when the SCM starts the service
	// (for example, "--service=run --enroll-url ... --name ...").
	Arguments []string
	// ManualStart, when true, registers a demand-start service instead of the
	// default automatic start.
	ManualStart bool
}

// Spec is a validated, fully-defaulted service description.
type Spec struct {
	Name           string
	DisplayName    string
	Description    string
	ExePath        string
	Arguments      []string
	AutomaticStart bool
}

// BuildSpec validates cfg and fills defaults. It returns an error if no
// executable path is given.
func BuildSpec(cfg Config) (Spec, error) {
	if strings.TrimSpace(cfg.ExePath) == "" {
		return Spec{}, errors.New("winservice: ExePath is required")
	}
	name := cfg.Name
	if name == "" {
		name = DefaultServiceName
	}
	display := cfg.DisplayName
	if display == "" {
		display = "trustctl agent"
	}
	desc := cfg.Description
	if desc == "" {
		desc = "trustctl non-human identity agent: enrolls with the control plane, maintains mutual TLS, and installs and rotates credentials on this host."
	}
	return Spec{
		Name:           name,
		DisplayName:    display,
		Description:    desc,
		ExePath:        cfg.ExePath,
		Arguments:      append([]string(nil), cfg.Arguments...),
		AutomaticStart: !cfg.ManualStart,
	}, nil
}

// CommandLine is the full service command line (executable plus arguments),
// quoting the executable path because it may contain spaces.
func (s Spec) CommandLine() string {
	if len(s.Arguments) == 0 {
		return `"` + s.ExePath + `"`
	}
	return `"` + s.ExePath + `" ` + strings.Join(s.Arguments, " ")
}

// WiXOptions parameterizes the MSI rendering.
type WiXOptions struct {
	Version      string // product version, e.g. "1.2.3"; defaults to "0.0.0"
	Manufacturer string // defaults to "trustctl"
}

// baseName returns the final path element, splitting on both Windows and POSIX
// separators (ExePath is a Windows path even when rendered on another OS).
func baseName(p string) string {
	if i := strings.LastIndexAny(p, `\/`); i >= 0 {
		return p[i+1:]
	}
	return p
}

var wixTemplate = template.Must(template.New("wxs").Funcs(template.FuncMap{
	"attr": xmlAttr,
}).Parse(`<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by trustctl winservice; edit the generator, not this file. -->
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Product Id="*" Name="{{attr .DisplayName}}" Language="1033" Version="{{attr .Version}}"
           Manufacturer="{{attr .Manufacturer}}" UpgradeCode="{{.UpgradeCode}}">
    <Package InstallerVersion="500" Compressed="yes" InstallScope="perMachine"
             Description="{{attr .Description}}" />
    <MajorUpgrade DowngradeErrorMessage="A newer version of {{attr .DisplayName}} is already installed." />
    <MediaTemplate EmbedCab="yes" />

    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFiles64Folder">
        <Directory Id="INSTALLFOLDER" Name="trustctl" />
      </Directory>
    </Directory>

    <ComponentGroup Id="AgentComponents" Directory="INSTALLFOLDER">
      <Component Id="AgentExecutable" Guid="*">
        <File Id="AgentExe" Name="{{attr .ExeName}}" Source="{{attr .ExeName}}" KeyPath="yes" />
        <ServiceInstall Id="AgentServiceInstall"
                        Name="{{attr .Name}}"
                        DisplayName="{{attr .DisplayName}}"
                        Description="{{attr .Description}}"
                        Type="ownProcess"
                        Start="{{.Start}}"
                        ErrorControl="normal"
                        Account="LocalSystem"
                        Arguments="{{attr .Arguments}}" />
        <ServiceControl Id="AgentServiceControl"
                        Name="{{attr .Name}}"
                        Start="install"
                        Stop="both"
                        Remove="uninstall"
                        Wait="yes" />
      </Component>
    </ComponentGroup>

    <Feature Id="AgentFeature" Title="{{attr .DisplayName}}" Level="1">
      <ComponentGroupRef Id="AgentComponents" />
    </Feature>
  </Product>
</Wix>
`))

// WiXSource renders the WiX (v3) source that builds the agent's MSI: it installs
// the binary and registers the Windows service derived from spec, so the
// installer and the runtime service agree on name, start type, and arguments.
func WiXSource(spec Spec, opts WiXOptions) (string, error) {
	version := opts.Version
	if version == "" {
		version = "0.0.0"
	}
	manufacturer := opts.Manufacturer
	if manufacturer == "" {
		manufacturer = "trustctl"
	}
	start := "auto"
	if !spec.AutomaticStart {
		start = "demand"
	}
	data := struct {
		Spec
		Version, Manufacturer, ExeName, Start, UpgradeCode, Arguments string
	}{
		Spec:         spec,
		Version:      version,
		Manufacturer: manufacturer,
		ExeName:      baseName(spec.ExePath),
		Start:        start,
		UpgradeCode:  upgradeCode,
		Arguments:    strings.Join(spec.Arguments, " "),
	}
	var b strings.Builder
	if err := wixTemplate.Execute(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}

// xmlAttr escapes a string for use as an XML attribute value.
func xmlAttr(s string) string {
	r := strings.NewReplacer(
		"&", "&amp;",
		"<", "&lt;",
		">", "&gt;",
		`"`, "&quot;",
	)
	return r.Replace(s)
}
